#+BEGIN_COMMENT
.. title: 塞斯．卡拉曼：價值投資中的 30 個重要投資思想
.. date: 2017-08-29 16:54:00 UTC+08:00
.. updated:
.. comments: true
.. tags: 汪汪財經
.. layout: post
.. category: investment
.. permalink:
#+END_COMMENT
#+OPTIONS: toc:nil ^:{}

來源：[[http://wawafinanceessais.blogspot.com/2017/08/30.html][汪汪財經：塞斯．卡拉曼：價值投資中的 30 個重要投資思想]]

塞思．卡拉曼是 Baupost 基金公司總裁，對價值投資有深刻研究，代表作有《安全邊
際》。由其管理的 BaupostGroup , 在過去 30 年中，在只用 5 成倉位的情況下，完成了
年復合增長率 20% 的奇蹟。

塞斯卡拉曼《安全邊際》中的 30 個重要思想

* 一、價值投資並不簡單

價值投資需要投入大量精力和努力，非一般嚴格的紀律，還有長期投資的視野。只有
少數人投入了做價值投資者所需的時間和精力，但這裡面能建立起合適的投資觀並成
功的人就更少了。就像大多數八年級的代數學生一樣，一些投資者只是簡單地記了幾
個公式或者規則就覺得自己天下無敵了，但很多時候他們並不知道自己到底在幹什
麼。想要在金融市場和經濟周期中獲得長期的成功，單純只靠觀察總結出幾條規則來
是不夠的。

投資的世界裡太多事情變得太快，所以我們需要明白規則背後的基本原理，這樣才能
知道為什麼有些事情會發生，有些事情不。價值投資不是靠長時間的學習和實踐就能
學習和掌握的，這種投資理念，要麼（天生適合你，所以）你一下子就能學會，要麼
你一輩子都無法真正得其精髓。理解價值投資很簡單，實操卻很難。價值投資者也不
是精於分析超複雜數據的巫師，他們也不會編寫出複雜的電腦模型去發現潛在價值，
尋找優質的投資機會。最難的部分是自律，還有判斷。價值投資者需要強大的自律能
力去拒絕那些不那麼優質的投資誘惑，需要足夠的耐心去等待真正優秀的機會，並且
可以準確判斷現在是不是最佳時機，該出手時就出手。

* 二、價值投資者的特性

自律，直到找到划算的投資機會再出手，這使價值投資者們看起來很像風險厭惡者。
自律對於他們來說是必需的，他們面臨的最大挑戰就是如何保持這份自律。價值投資
者意味著總是遠離人群，挑戰常規，甚至頂著盛行的投資風向逆行，這條路不可謂不
孤獨。在長期市場估值偏高的時間段裡，價投者的表現有時和其他的投資者、或者整
個市場比起來都會不盡如人意，甚至“可怕”。但長期來看，價值投資非常成功，所以
你們會發現很少有價投者會放棄這種投資理念。

* 三、投資者的最大敵人

如果有投資者可以成功預測市場未來的走向，他們肯定永遠都不會去當價值投資者。
誠然，當證券的價格穩步上升時，價投本身就是一個缺陷；不受歡迎的證券漲得沒有
公眾喜歡的幅度大。另外，當被高估的市場被正確估值時，價投者也是討不了巧的，
因為他們很快就會需要賣掉手上的票。所以，當價投者的最佳時機是市場下行時。那
些原先只關注上行因素的投資者們正在吞盲目樂觀的苦果，這種時候，任何導致下行
的風險因素都會被看得很重，而價投者因為用了一定的安全邊際來投資，所以能夠保
護他們免受市場下行的巨大損失。能夠預測市場未來的投資者應該全副投入，用借來
的錢，在市場上行之時進入，再在它下跌之前出來。不幸的是，許多投資者雖然聲稱
自己有這樣的能力，但實際上並沒有。（至少我個人是從來沒見過一個。）對於那些
明白自己做不到預測市場的人，我非常推薦價值投資，這在所有的投資環境裡都是一
個安全又成功的策略。

* 四、一切皆與思維模式有關

成功的投資需要建立起合適的思維模式。投資是嚴肅的，絕非兒戲。假如你參與到金
融市場中來，很重要的一點就是你所有的動作都應該是以一個投資者的角度出發，而
不是觀察者，確定你明白這兩者的區別。無疑，投資者能說得出百事可樂和畢加索的
區別：百事可樂是投資對象，而畢加索的作品則是收藏對象。當你把辛辛苦苦存下來
的錢和未來的金融證券放在有風險的地方時，不了解兩者區別的代價會非常非常高。

* 五、別找市場先生要建議

有些投資者——其實是觀察者會從市場先生那兒尋求投資建議——這是不對的。當他
們發現市場先生給一個票定價偏低，就會忘記市場先生本身是不理性的事實，忘記自
己曾經對這些票的真正價值做出的估算而瘋狂賣掉自己手上持有的貨。當他們看到市
場先生給某個票提價時，又會因相信他無所不曉而跟著高價位買入。但事實是，市場
先生什麼都不懂，他誕生於成千上萬投資者賣出買入的行為之中，而很多時候這些投
資者的行為卻並非出於投資原理。衝動的投資者和觀察者會無可避免地遭受損失；但
深知市場先生間歇性無理取鬧這種特性的投資者，則可以利用這一點，在長期的投資
獲得成功。

* 六、股價 VS 商業真相

路易斯．洛溫斯坦(LouisLowenstein)已經警告過我們，不要把一個公司在商業上真正
取得的成功和在股市上取得的成功搞混。一個公司的股價上漲不代表它發展狀況良
好，同樣地，股價下跌也不代表一定是它公司業務發展不好或者價值下跌。所以投資
者一定要學會分辨股價波動和潛在商業真相。投資者們如果發現整體的趨勢是大家都
在盲目地跟風買入或賣出，那麼他們一定要抵擋住這股趨勢才行。當然你不能無視市
場，因為市場裡蘊含著投資機會，忽視它等於犯錯，但你一定要為自己著想，不要讓
市場牽著你的鼻子走。

* 七、股價 VS 價值

價值與價格掛鉤，但並不只取決於其價格，為此要多留意你的投資決策。如果你將市
場先生看作投資機會的創造者，會為你創造那些價格和公司價值不符的投資機會，那
你就有了成為價值投資者的先決條件。但你如果減持把市場先生看作是你的投資顧
問，那我建議你還是僱別人來為你打理錢財比較好。股票價格會因為各種原因而變
動，你無法判斷現在的股價反映了什麼樣的預期，所以投資者們必須要透過股價看企
業本身的商業價值，在投資過程中不斷比較這兩者。

* 八、情緒會擾亂投資

不成功的投資者都被情緒支配。他們不會冷靜理智地面對市場波動，出於貪婪和恐
懼，他們會很不理智。想必我們都認識一些平時舉止負責、從容不迫，但在投資時會
進入「狂暴狀態」的人。他們會把自己經過很多個月，甚至很多年的辛勤工作和自律
存下來的錢在短短幾分鐘之內就投資掉。這些人在買一個音響或者照相機之前會願意
讀上好幾本消費者指南，前往比較很多家店，但卻不願意花點兒時間去好好研究從他
的一個朋友那兒聽說的股票。在購買電子攝像產品時的理性在投資股市的時候反而沒
有了。

* 九、股市≠賺快錢的地方

許多不成功的投資者把股市當成一個無須努力就能賺快錢的地方，而不是一個投資資
本以求更好收益的地方。誰都想毫不費力地賺快錢，但是這種想法恰恰完美反映了投
資者們的貪婪。貪婪促使他們去尋求投資成功的捷徑。他們並不打算讓財富慢慢積
累，而是想靠著一些“新鮮”的消息快速生財。他們也不會停下來想想，給他們消息的
那些人是怎麼能夠不違法就獲得這些消息的？為什麼？如果真的如此有價值，為什麼
會對他們公開？貪婪同樣表現為盲目樂觀，更隱形一點的，則會表現為面對壞消息來
臨時懈怠。最終，貪婪會使投資者們把他們的目標從「獲得長期收益」變成「短期獲
利」。

* 十、股市的循環

市場上所有的流行趨勢終會完結。股價最終會變得太高，供應最終會趕上需求，然後
趕超需求，天花板就會來臨，接下來就會下行。投資熱點總是有循環的，投資者們也
一定會接受它們。公正來說，要分辨一個趨勢只是投資界的熱點還是現實的商業潮流
並不容易。實際上，許多投資熱點就誕生於商業潮流，這種趨勢是理應反映在股價上
的。但是，當股價上升到一個超過它本身估值的水平時，這個潮流就會變得危險。

* 十一、投資大鱷是如何失誤的，他們的表現為何弱於大盤？

如果忽略機構投資者可能帶來的可怕後果的話，他們的行為其實還挺搞笑的。他們搜
刮投資者們辛辛苦苦賺回來的數十億錢財，然後在沒有經過深度研究和分析就進行一
個又一個的投資。現在盛行的心態就是要一致從眾。人們可以接受隨大流帶來的平
庸，無法接受特立獨行時面臨跑輸大盤的風險。投資經理們這種追求短期收益的心態
使得「機構投資者」變成了一個充滿矛盾的稱謂。

許多投資經理的報酬模式不是基於他們做出的成績，而是基於他們管理的資金佔比資
金總額的多少。這就會刺激他們想要不斷擴大自己管理的資金量，這樣就能產生更多
的費用。但實際上從機構的角度出發來看，提升資金的投資回報率才是獲利最高的途
徑，（所以經理們的心態）使機構們愈發難獲得好的投資表現。但本來投資經理們只
要調整自己的行為偏好，這種機構與客戶之間的矛盾就完全可以解決。

* 十二、短期相對回報的德比大戰

就像追著自己尾巴轉圈的狗狗，絕大多數機構投資者都被困在追求短期相對回報的德
比大戰中。有一個機構裡的基金經理們的表現甚至要按小時計費；不計其數的經理每
天的業績都要被拿來和其他公司的同行比較。頻繁的對比和排名只會更加強化他們想
要追求短期投資收益的觀點。如果他們的短期收益表現很差，就要受罰，所以也可以
理解為什麼想要他們維持長期投資的信念很難。如果他們堅持長期收益的做法，很可
能就會失業。不了解機構投資者們的這個特性就去盲目投資，就好比在異國自駕行卻
不帶地圖。你可能最後還是會到達一開始的目的地，但旅程所需的時間肯定更長，你
還得承擔途中迷路的風險。

* 十三、首先，避免虧錢華倫．巴菲特經常說投資的首要定律就是「不要虧錢」，第二條則是：「永遠牢記第一條。」

我也認為避免虧錢應是每個投資者的首要目標，但這不是說投資者不應承受一丁
點兒虧錢的風險。“不要虧錢”更多地是指在往後的幾年中一個人的投資組合不
要導致資本大量流失。沒有人想要承受損失，你也無法通過檢驗絕大多數投資者
和投機者的行為來證明。我們絕大多數人都有強烈的投機衝動，免費午餐的誘惑
總是強烈的，特別是身邊的人好像都已經吃到了。當別人都在貪婪地追逐利益，
經紀人又在給你推薦時下最熱的 IPO 股票時，你是很難靜下心來想想虧錢的風
險的。但依然，避免虧錢，是保證你炒股賺錢的篤定之法。

* 十四、臨時價格波動的相關性

投資一個股票有可能會給你造成永久性的損失，也有可能其股價會出現臨時性的波
動，這種波動和公司背後的潛在價值並無關係。很多投資者把股價的波動看作巨大的
風險：只要股價下跌，不管這家公司根基如何，他們都會覺得它岌岌可危。但價格的
臨時波動真的有風險嗎？有，但這和那些會造成永久損失的投資不一樣，而且這種風
險只對特定情況裡的某些投資者有效。

當然，要去分辨短期的供求關係帶來的價格波動和企業根基受損帶來的價值變化，是
很難的。事實只有在真正發生了之後才會變得明顯。顯然，投資者可以避免買高了或
者買入之後公司其價值就發生退化，但不可能不面對股價的短期波動。實際上，他們
應該知道價格波動一定會存在，如果他們一丁點兒的波動都接受不了，那還是別炒股
了。如果你真的以折扣價買到了一個有價值的股票，短期的價格波動有影響麼？長期
來看，沒有太大影響，一個公司的價值最後總會在其股價上真實反映出來的。

諷刺的是，長期來看股價會上升，這和短期市場對股價的走向影響正好相反。也就是
說短期價格下滑其實增加了長期投資者們的收益。但在幾個情況下，長期投資者也會
對關注短期價格波動，比如，那些急於賣股票的人就要受市場價格擺佈。成功投資者
的一個訣竅就是，想賣的時候再賣，而不是被迫賣。還有，如果他們買的那個公司真
的有問題時，投資者們也應該關注其股價變動。如果一個公司近期必須要靠籌集更多
資金存活，那它將出現的股價變動某種程度上也決定了那些投資了這個公司的股票或
者債券的人的命運。

第三種情況則是市場先生有時候（會通過股價波動來創造）非常誘人的買賣機會。
（股價下跌時，）如果你手上有現金，你就可以在此類機會中獲益。但如果市場下行
的時候你所有錢都已經投了進去，你的投資組合價值很可能會下降，因為你失去了用
較低價格買入優質股票的獲益機會。這就是機會成本，就是說你不得不放棄了未來可
能出現的好機會。如果你手上的股票流動性和市場性很差，那這個機會成本就更高。
買入流動性不足的股票會使你錯失更好的投資機會。

* 十五、合理持續的收益>驚人卻不穩定的收益

看重複利的一個必然結果就是，只要損失慘重一次，就很難恢復。這能一下子毀掉一
個人多年成功的投資成果。換句話說，對於一個投資者而言，在有限風險的情況下獲
取持續良好的回報比在風險相對較大的情況下獲得不穩定且有時「波瀾壯闊」的回報
可能要更好一些。比如，一個在過去十年保持年收益率為 16%的投資者和一個前九年
每年都賺 20%然後最後一年損失掉 15%的投資者相比，前者可能最後賺的錢要更多。

* 十六、為最壞的情況做打算

避免虧錢的原則會使投資者在任何情況都生存下來甚至壯大。但壞運氣總會到來，人
不可能永不犯錯。精明、有遠見的投資者相信金融災難總會到來，並以此為前提管理
自己的組合。逆境無法被預測，所以必要的時候，一定要放棄一些短期的回報，當作
應對逆境繳納上的保險。

* 十七、注重過程，而非結果

許多投資者給自己設定了一個具體的回報率目標，這是錯誤的。不幸的是，定了目標
不代表就一定會實現。也就是說，不管你定了什麼目標，最後都有可能不達標。如果
你將市場先生看作投資機會的創造者，會為你創造那些價格和公司價值不符的投資機
會，那你就有了成為價值投資者的先決條件。假設你給自己定了一個每年賺 15%的目
標，但它並不會教你如何才能達標。投資回報和你的努力程度或者意願的強烈程度不
是直接正相關的。一個挖溝的工人加班一小時可以拿到更多錢，計件工完成的件數越
多，賺得越多。但對於投資者來說，不是你思考得更努力或者投入更多時間就可以獲
得更多回報。投資者所能做的，只能是持續堅持自律嚴格的方法。假以時日，一定會
有回報。與其設定一個具體的投資回報率，就算它看起來很合理，都不如盯著風險
（不要讓自己虧大錢）。

* 十八、等待最佳的擊球機會

華倫．巴菲特曾經用棒球類比價投者的自律。一個長期導向型的投資者就好比擊球
手，比賽中沒有出現好球，也沒有出現壞球的時候，擊球手可以對幾十個，甚至幾百
個擊球機會無動於衷，其中不乏別人看到很可能就會揮棒的機會。價投者就是比賽的
學習者，不論擊中與否，他們都從每一次揮棒中學習經驗。他們不會受別人的表現影
響，只關注自己的成績如何。他們有無盡的耐心，願意等，直到一次絕佳的擊球機會
出現在他們面前——一個被低估了的投資機會。價投者不會投資那些他們沒有十分把
握的，或者那些風險奇大的公司。和價投者不同，絕大多數的機構投資者有強烈的慾
望一直滿倉。

他們表現得好像裁判一直在讓他們揮棒似的，因此他們迫切地感到自己應該每球必
揮，為了揮棒的頻率犧牲了選擇揮棒的效率。許多個人投資者就像業餘玩家，單純地
無法分辨哪一個才是好的擊球機會。缺乏鑑別力的個人投資者和受限的機構投資者，
當得知許多市場參與者也和他們一樣，感覺自己應該頻繁揮棒的時候，也能從中獲得
安慰。對於價投者來說，擊球不只應在擊打區域內，還應該在他的「甜蜜點」裡。

當投資者沒有被迫在時機成熟前投資的時候，表現才最好。有時候機會來了，但他們
可能依然不揮棒，因為在一個普遍估值偏高的市場裡，最便宜的那個股票也依然是被
高估的。一個安全的投資機會如果有 10%的回報率和一個同樣安全但是回報率有 15%
的投資機會，你肯定會想要選擇後者。有時，許多好機會接踵而至。比如在一個普遍
恐慌的市場裡，被低估的股票數量就會上升，被低估的程度也會上升。相對的，一個
普遍看漲的市場裡，被低估的股票數量和程度都會下降。當好機會充足時，價投者就
可以從中認真篩選出他們覺得最具吸引力的機會。但是，當好機會稀缺時，價投者一
定要表現出強大的自律性，這樣才能保證估值的過程沒有錯誤，不會花多了錢。就是
說，投資者應該永遠避免打壞球。

* 十九、商業估值的複雜性

如果你覺得能看透任何一項投資決策背後的所有特性和邏輯的話，那你就大錯特錯
了。總會有問題沒人回答，該問的問題也經常沒人問。就算現在能夠完美地了解某一
項投資決策，但還是要知道，絕大部分投資決策所依據的未來結果都是不可預測的。
就算一項投資中的所有細節都被知道了，但一個公司的價值也不是刻在石頭上人盡皆
知的，這才是最複雜的地方。如果公司價值可以保持恆定，股價就像行星一樣繞著價
值轉，那投資就會變得簡單得多。如果你不確定一個公司的價值，那你怎麼能確定你
是以折扣價買入其股票呢？答案就是，不能。

* 二十、對估值精益求精？

許多投資者堅持在投資過程中做到精確估值，在一個充滿不確定性的世界裡精益求
精，但問題是，一個公司是不可能被精確估值的。公佈出來的賬面價值，收益和現金
流說到底都只是根據一套相對嚴格的標準和實踐做出來的合理的會計猜測，它更多的
追求一致性而不是為了反映公司的經濟價值。預測出來的數據也不會那麼精確，幾千
美元的房子都很難準確估價，更何況是給所處環境龐大又復雜的公司估值？我們無法
給公司正確估值，而且公司價值也總是在變，它會隨著大量的宏觀、微觀以及市場相
關的因素不停波動。

在任意一個靜止的時間節點，投資者都無法精確估出公司的價值，更何況還要隨著時
間變化結合所有可能影響估價的因素來不斷調整他們的估計？所以，想要精確給一個
公司估值，只會得出非常不准確的數字。而問題是，大家總會把「可以精確估值」和
「“可以準確估值」搞混。任何人，只要有計算器，就可以算淨現值(NPV)和內部收益
率(IRR)。電子製表工具的出現讓人們以為自己能夠做出精確深度的分析了，殊不知這
種計算過程是非常隨意的，從而進一步惡化了這個問題。大家都覺得產出很重要，但
卻經常忽略在生產過程中，「垃圾進，垃圾出」才是正確寫照。

在《證券分析》中，葛拉漢和大衛．多德就討論過價值區間的概念：「證券分析最關
鍵的一點不要痴迷計算一個證券精確的內在價值。你只需要確信其 *價值足夠* ，比如
說，去保護其債券價格或者股票價格相對其價值來說不要太高或太低，就好了。目標
是這個的話，對 *內在價值有一個模糊大概的估算就夠了* 。」的確，葛拉漢經常會去算
每股淨運營資金的指標，用來大概估算一個公司流動價值。他頻繁使用這個粗略估算
的指標，恰恰就是在無聲地向大家承認，他也沒有辦法給一個公司進行更精確的估值
了。

* 二十一、為什麼需要安全邊際？

價值投資需要投資者時時自律，如此才能以非常划算的價格買到實際價值遠高於此的
股票，並且能一直抓著不賣，直到其價值被更多地認可。「划算」是整個過程的關
鍵。由於投資和科學一樣有藝術，所以投資者需要安全邊際。考慮到在這個複雜、無
法預測又變換迅速的世界裡，人人都有可能犯錯、運氣不好，還可能遭遇激烈的市場
波動等因素，當你能夠以遠低於一支股票真實價值的價格買它的時候，你就算是有了
安全邊際了。葛拉漢說過：「安全邊際的大小取決於你付的錢。任何一個股票，假設
某一個價位時安全邊際很大，再高一點的時候就變小了，再高一點，就沒有安全邊際
了。」價投者需要安全邊際，這樣才有空間承受長時間累計下來估值不准、運氣不好
或者分析錯誤所帶來的損失。安全邊際是必須的，因為：

- ** 估值是一項藝術，沒法精準；
- ** 未來是無法預測的；
- ** 投資者也是人，是人就會犯錯

* 二十二、需要多大的安全邊際？

答案因人而異。你覺得自己的運氣會有多壞？能承受多壞的運氣？你能接受的商業價
值波動幅度是多少？你能忍受多嚴重的錯誤？歸根結底就是，你有多少可輸？絕大多
數投資者買股票的時候不會考慮安全邊際。那些把股票看作一張張能拿來交易的紙的
機構投資者和總是滿倉的投資者是無法獲得安全邊際的。總是盲從市場趨勢和潮流的
貪婪個人投資者亦如此。而那些買了華爾街承銷的股票或者金融市場衍生品的投資者
能獲得的唯一安全邊際則往往是危險的。那麼投資者如何確保獲得安全邊際？

- 永遠要以超級划算的價格買入實際價值高得多的股票，比起無形資產嗎，應更
  偏好有形資產（但這也不是說那些擁有大量無形資產的公司中就沒有好的投資
  機會了）；
- 當出現了更划算的股票時，替換掉現在手中的；
- 當某個股票的真實價值開始反映到股價上來時，賣掉換成錢，如有必要，一直
  抓著，直到你發現新的好的投資機會。

投資者們需要搞明白的，不僅是自己手上的票是否被低估了，還有為什麼被低估？
當你再沒有理由繼續持有某個股票時，你就要搞明白當初為什麼買，現在為什麼
賣？找那些會有催化劑的股票，而且是能夠直接加速企業真實價值體現的催化劑。
優先看那些管理層優秀，並且管理層自己也持有公司股票的公司。最後，當情況
允許，前景不錯時，差異化你的持股，套期保值。

* 二十三、價值投資的三要素

** 1.自下而上：
價值投資中自下而上的策略就是，通過基本面分析找投資機會，每次找一個。價投者
會一個一個找有沒有划算的股票，就公司自身分析其每一個情況。這個策略可以被簡
單描述為：“買個划算的股票，然後等。”投資者一定要學習給企業估值，這樣在看到
機會的時候才能抓住。

** 2.絕對回報導向：
絕大部分的機構投資者和許多個人投資者採用的都是相對回報導向的做法。他們投資
的目標要麼就是表現比市場好，要麼么就是比其他投資者好，卻顯然不關心他們的絕
對回報是正的還是負的。通常，較好的相對回報，特別是短期的相對回報，可以通過
模仿別人或嘗試看透別人將要採取的行動來獲得。相反地​​，價值投資者一定是絕對
回報導向的。他們只關心回報是否達到了自己的投資目標，而不是去和整體市場或者
其他投資者比。好的絕對回報要靠買入被低估的股票，在其真實價值被更多地認可時
賣掉。對於大多數投資者來說，絕對收益才是真正要緊的。

說到底，你又花不了「相對收益」（因為相對收益不是實打實賺到的錢）。絕對收益
導向的投資者通常會看問題的角度通常會比相對收益導向的投資者更長遠。一個相對
收益導向的投資者是無法忍受表現長時間弱於大盤的，所以他們就會去買時下流行的
股票。因為不這麼做會影響他們的短期投資表現。事實上，相對收益導向的投資者會
有可能避開那些長期的絕對收益會很好，但有可能會讓他們面臨近期的表現弱於大盤
的投資機會。相反，絕對收益導向的投資者就更喜歡那些不那麼被大眾喜歡的股票，
這些股票需要更多時間才會有回報，但虧錢分風險也更小。

** 3.風險與回報：
當別的投資者都要全神貫注地計算他們能賺多少時，其實全然不關心他們可能會虧多
少。但價投者既關心回報，也關心風險。風險就是每個投資者分析的某個投資行為會
虧錢的可能性。勘探一個油井時發現它就只是一口枯井，這就叫風險。債券違約，股
價跳水，這都是風險。但是，當油井噴湧，債券按時履約，股價強勢反彈時，我們投
資時就可以說毫無風險麼？當然不是。事實是，在大多數情況下，就算是在事後試圖
總結一項投資的風險，也沒法比做決定時了解得更多。投資者們想要抵消風險，能做
的其實很少：足夠多樣化自己的持有；在適當的時候套期保值；投資時尋找一定的安
全邊際。正因為我們不會，也沒法得知投資可能出現的所有風險，我們才需要努力保
證自己用折扣價買股票。追求划算的買賣，可以在出問題的時候提供緩衝的保護。

* 二十四、為成長性多付太多

太多太多的投資者只根據自己對一個公司未來成長性的預測就決定投資這個公司。說
到底，一個公司賺錢更快，它的現值就更高。但是成長性導向的投資者會面臨幾個難
題。首先，這些投資者對自己預測未來的能力經常都太過自信。第二，那些快速成長
的公司，投資者對它們的年增長率的細微差別都會在給公司估值的時候帶來巨大不
同。還有，當很多人都想要買成長性好的股票時，這個統一化的行為就很可能會抬升
把公司股價抬到一個超出其根基的水平上。

「商業名人堂」的成員總走馬燈地換，總會有投資者被金錢誘惑，因為自己現在的強
健表現就做出過於樂觀的預測，這樣往往會使他們為一個中等的公司多付錢。投資增
長性還有一個難題，就是這個導向的投資者把成長性簡化成一個簡單的數字。但是實
際上，一個公司的成長由許多許多動態部分組成，而每個部分的可預測性都不同。舉
個例子，對於任何公司來說，收入增長可以有很多種意思，可以是總人口可預見性的
增長帶來的銷售量增長，或者是消費者對此產品的使用率上升，或者是市場份額上
升，有可能是產品的普及性提高，或者就是價格上升。

* 二十五、成長性「詐騙」有投資者經常在評估未來時過於樂觀。

一個很好的例子就是大家看到公司沖銷行為時的反應。這個會計行為使公司可以完全
自行進行內部賬目的清理，可以馬上擺脫自己賬面上的不良資產、收不回來的應收賬
款、壞賬、以及任何公司在進行沖銷時隨之而來重新調整的支出。這種行為是典型的
受華爾街分析師和投資者一致歡迎的行為。壞賬沖銷過的公司可以交出一份更好的成
績單，回報更好，利潤增長幅度更高。然後，這個“粉飾”過的結果就會被算入對未來
的預測中，進一步推高其股票價格。然而，投資者不應該輕易把這個公司的壞賬歷史
也隨之一筆勾銷。

* 二十六、保守主義和成長性投資

價投者應該如何去分析和預測不可知的未來？唯一的答案就是保守主義。所有的預測
都有可能犯錯，樂觀的人總是把自己置於危險的枝幹上。對於他們這種情況，每一件
事情就一定要在正軌上，不然損失就會持續。但是保守的預期就可以很容易達到甚至
超過。價投者應該保守地預期，然後以極大的折扣價入手價值遠高於其股價的股票。

* 二十七、要做多少研究和分析才算夠？

有些投資者在做某項投資之前巴不得自己完美掌握了相關的所有知識，他們研究這些
公司，直到他們已經對公司瞭如指掌。他們去研究行業和競爭情況，去聯繫公司的前
僱員，行業資訊和分析師，自己去熟悉頂尖的經營管理知識。他們分析公司過去十
年，甚至更久之前的財務報表和股價走勢。這份勤奮令人佩服，但有兩個缺點。

1. 不管你做了多少研究，有一些信息你就是找不到，所以投資者要學會接受不
   足的信息，而不是企圖得知所有。
2. 就算一個投資者可以獲知一個公司的所有信息，他/她的投資也不一定會因此
   獲利。當然，這不是說基本面分析就沒用了。它肯定有用。大部分投資者力
   求確定性和精確性，避免難以獲得信息的情況，殊不知都在做無用功。低價
   總會伴隨極高的不確定性。當不確定性被解決的時候，價格也會水漲船高。
   不要等知道所有信息了才投資，這樣的投資者可以經常獲利。他們承受的不
   確定性的風險，最後也能為他們帶來豐厚的回報。

當其他投資者還在苦苦鑽研公司之前一個還沒應答的細節問題時，他們很可能就錯失
了用極低價買入一個有安全邊際的股票的機會了。

* 二十八、價值投資與反向思維

從本質上來說，價投者就是「唱反調」的人。不被大家喜歡的股票才有可能被低估，
流行的股票則幾乎從來不會出現這種情況。「羊群」買的就是被喜愛的股票。由於大
家對它們的預計都很樂觀，這些股票的價格已經被抬得很高了，不大可能有還沒被發
現的價值了。如果大家都買的股票是沒有價值的，那哪裡有？在他們賣掉的、沒有發
現的、或者忽視的股票裡。當人們都在賣一個股票時，它的股價就會暴跌到不合理的
程度。而那些被忽視的、沒有名氣的、或者新上市的股票也有可能因為同樣的原因而
被低估。

投資者會覺得很難成為一個「唱反調」”的人，因為他們從來不知道自己到底是不是
對的，以及何時才會被證明是對的。由於和大家背道而馳，他們在開始階段幾乎都會
被看作是做錯的那方，還會承受損失。相反，「羊群」裡的成員在相當一段時間裡則
表現得似乎是正確的那方。相比起其他人，唱反調的人不僅在最初，甚至在隨後的一
段時間裡都會看起來做錯了，因為潮流可以無視公司的真實價值而持續很久。然而，
和大家持相反意見也不總是湊效的。當一個眾所周知的觀點不會對眼前的事造成影響
時，就算逆流而上也不會獲得什麼意外收穫。就好比大家總是覺得明天會有太陽，但
其實這個觀點本身並不會影響之後的結果。

* 二十九、指數謬論

對於價投者來說，做指數這個概念是非常愚蠢，甚至非常有危害性的。華倫．巴菲特
發現，「任何一種形勢的比賽，金融的、腦力的或者體力的，如果有一個競爭對手能
讓你切實體會到任何嘗試都是無意義的話，其實是一件極大的好事」。我認為隨著時
間過去，價值投資者終究會表現得強於大盤，而其他那些企圖與之比肩的人都是懶惰
或短視的。

做指數是一個有著危險缺陷的策略，理由有幾個。第一，當越來越多的投資者採用這
個策略時，它就失去了作用。雖然指數化思想在有效市場上是可以實施的，但是採用
這個方法的投資者越多，市場就會變得越來越沒有效率，因為越來越少的投資者去研
究以及做基本面分析了。當指數里有一個或者更多的股票由於破產或者被收購而需要
被替換時，另外一個問題就會出現。

為了跟上自己指數的表現，投資者會傾向於滿倉買入指數裡的組成股票，而那些被替
換進來的股票也一定會馬上被成千上萬的指數組合型基金經理買。由於缺乏流動性，
一個新股票被加進去指數的第一天，由於指數者的哄搶，股價往往會高漲。但是這個
公司的根基並沒有任何改變，也沒有什麼新的東西使它變得比前一天更有價值。實際
上，就只是因為這個股票被加進了指數里，人們就願意為它支付更多。更重要的是，
正如巴菲特所說：「因為編制指數獲得了成功，於是強化了指數本身的表現，於是又
反過來促進更多的編制指數行為，於是一個自我強化的反饋迴路產生了」。

* 三十、危險之地

對於投資者來說，華爾街可以是很危險的。你只能在那兒做生意，但你一定要時刻戒
備。華爾街人的標準行為就是追求最大化的個人利益。這個導嚮往往是短期的。你要
承認這一點，接受它，與它共事。如果你能在和華爾街精英們做生意時牢記這一點，
你就可以成長。但如果你指著華爾街來幫你，你就永遠別想著能投資成功了。
