#+BEGIN_COMMENT
.. title: alsa equaler
.. slug: alsa-equaler
.. date: 2018-01-15 06:20:29 UTC+08:00
.. tags: Linux, alsa, mpd, music
.. category: computer
.. link:
.. description:
.. type: text
#+END_COMMENT

音響要好聲，空間才是王道[fn:1]，没有 DRC 前，先試試等化器[fn:2]，也許調一調就可用啦。
在 archlinuxl 中，我用的是 alsa 的架構播放音樂，
Archlinux WIKI 的 [[https://wiki.archlinux.org/index.php/Advanced_Linux_Sound_Architecture][Advanced Linux Sound Architecture]] 已說明等化器的安裝及設定，照做即可。

[fn:1][[http://www.miaofoundry.url.tw/products-and-services/DRC/][音樂再生首要難題 -- 空間]]
[fn:2][[http://www.miaofoundry.url.tw/products-and-services/DRC/whats/DRC-vs-others/][等化器(EQ)]]

* install
#+BEGIN_SRC sh
yaourt -S alsaequal
#+END_SRC

* config
在 =/etc/asound.conf= 加上以下設定：

#+BEGIN_EXAMPLE
ctl.equal {
    type equal;
}

pcm.plugequal {
    type equal;
    # Modify the line below if you do not
    # want to use sound card 0.
    #slave.pcm "plughw:0,0";
    # by default we want to play from more sources at time:
    slave.pcm "plug:dmix";
}

# pcm.equal {
# If you do not want the equalizer to be your
# default soundcard comment the following
# line and uncomment the above line. (You can
# choose it as the output device by addressing
# it with specific apps,eg mpg123 -a equal 06.Back_In_Black.mp3)
pcm.!default {
    type plug;
    slave.pcm plugequal;
}
#+END_EXAMPLE

* reboot
讓 alsa 可用等化器

* 調整等化器
執行
#+BEGIN_SRC sh
alsamixer -D equal
#+END_SRC

PS. 用 Q,W,E,Z,X,C 可分別調整左右聲道的音量。

* mpd issue
總是會連不上 mpd server，後來在 WIKI 中讀到一段話：

#+BEGIN_QUOTE
Note that configuration file is different for each user (until not
specified else) it is saved in ~/.alsaequal.bin. so if you want to use
ALSAEqual with mpd or another software running under different user,
you can configure it using

$ su mpd -c 'alsamixer -D equal'

or for example, you can make a symlink to your .alsaequal.bin in his
home...
#+END_QUOTE

我在 =/root= 目錄下，建一個連到主目錄 =.alsaequal.bin= 的連結，
mpd 即可使用，瞎打誤撞。
