#+BEGIN_COMMENT
.. title: 癌症是自己養出來的
.. slug: cancer-food-exercise
.. date: 2018-08-06 17:10:27 UTC+08:00
.. status: draft
.. tags: cancer
.. category: life
.. link:
.. description:
.. type: text
#+END_COMMENT
#+OPTIONS: num:nil toc:nil ^:{}
#+LANGUAGE: zh-TW

【來源】[[https://health.businessweekly.com.tw/AArticle.aspx?ID=ARTL000105718&p=1][工作多、壓大、體溫低，癌症是自己養出來的...奇蹟抗癌 30 年！名醫這樣擺脫癌體質(抗癌,午睡,腹式呼吸,偏方,猛爆性肝炎,截肢,腺體) - 非讀 BOOK - 防癌 - 良醫健康網 - 商業周刊（百大良醫）]]

要治好癌症，飲食、運動、快樂的心

【原文】如下：
* 輔助療法幫助調養身體

美國國家衛生研究院於 1998 年成立癌症輔助療法辦法室，目的在促進輔助醫療
與正統醫療間的互動，任務之一就是希望找到抗癌輔助食品。

長期在醫療體系裡，我對於照顧身體的觀念，一直都來自正規醫療知識，對於所
謂的輔助療法都視為「另類療法」、「偏方」，但深入文獻研究，才知道其中有
許多寶貴的價值。

早期我在行醫過程中，如果有病人詢問可否使用草藥偏方，我多半會勸阻，主要
是因為：藥用植物的醫療效果都屬於經驗值，普遍上沒有經過科學性的實驗驗證，
臨床報告也不充足，所以在治療上有許多不確定性。我擔心病人使用未經科學驗
證的偏方，服用時也有可能與西藥相互排斥，而產生無法預知的風險和後果，但
是這並不表示藥用植物沒有療效，只是必須加強科學驗證才能納入安全醫療的資
源內。

因為許多人在尋求藥用植物治療時，常因草本植物製作過程，未經嚴謹管控，含
有過量重金屬物質，造成服用者急性腎衰竭或猛爆性肝炎，這類案件相信大家都
時有耳聞；當然也有少數康復的案例，且經媒體大肆宣染，誤導民眾以為是「神
藥」。未經深入了解，僅憑報導口耳相傳，民眾往往一窩蜂的去購買和服用，許
多人因此耽誤治療，即使提起醫療訴訟也求助無門。

像是曾經風行一時的癌症草藥治療風潮，如：明日葉、紫杉醇等，都如曇花一現，
熱潮一過就復歸沉靜，但還是有人確實因盲目使用而耽誤病情，甚至暴斃猝死的
後遺症風暴，值得大家警惕。

由於癌症是攸關生命安全的重大疾病，傳統藥用植物在進行搭配使用時，必須非
常小心。尤其在份量、效用，都必須有嚴謹的科學驗證，才不會使患者受到更大
的傷害，或是阻礙了正規醫療的治療效果。

如果要自行使用藥用植物作為輔助醫療，一定要使用經過科學驗證、確認具有抗
癌效果，並經過無毒性的檢測，這種藥材或配方才能放心使用。否則就是在拿自
己的生命開玩笑。

* 含氧量夠，身體才有足夠力量抗癌

我們要經常有意識地讓身體做深呼吸。懷著要將體內毒素排出的心情呼氣，然後
慢慢把空氣吸進來。以呼氣時縮腹，吸氣時鼓腹的要領，進行腹式呼吸。

*腹式呼吸*可以使紊亂的自律神經恢復平衡，有助於提升免疫力。新鮮空氣進入肺
部也能增進新陳代謝，改善血液循環。不僅如此，每次呼吸，肺部都會上下活動，
肺部與腸子之間的橫隔膜受到刺激，就會跟著活化腸子，因此呼吸對清理腸子也
有幫助，持續做腹式呼吸也能讓人逐漸放鬆。

人體有五種流動的系統：血液與淋巴、腸胃、尿、從肺部吸入的空氣，以及氣。
要維持健康，就必須使這些系統通暢無礙，而促進流動的方式就是運動。充分活
動身體可以提高基礎代謝、免疫力和抵抗力，也能增加氣力，並活化體內酵素。

可配合自己體力，每星期做 4、5 次的運動，像是走路、游泳、打高爾夫球、做
肌肉訓練，也可以定期打太極拳、做瑜珈等運用呼吸的運動。但運動必須適度才
能達到效果，*太過激烈的運動，造成運動過度反而會增加體內的活性氧，加速細
胞老化*，反而使身體情況變得不穩定。

我習慣利用中午看診休息的時間，稍微*午睡一下*，然後和太太到附近的公散步做
一些柔軟運動。這是從骨癌術後就養成的習慣，除了幫助術後的復健外，主要也
是希望藉大自然最天然的療癒力量，幫助身體的復原和重建。

人為什麼會罹癌，原因其實很簡單，工作過度、壓力過大，以及伴隨著壓力而來
的血液循環障礙等。低溫、低氧的環境，更是癌細胞最喜歡的環境。所以當壓力
引起的低溫低氧成為生活的常態時，身體細胞就會發生病變了。

要讓癌腫瘤萎縮絕對不是什麼難事，只要讓身體營造一個癌細胞難以適應的環境
就好了。換句話說，就是讓身體脫離低溫低氧的狀態，將它轉變為粒腺體的環境
即可。

所以，擔心罹癌的人首先應該檢討自己的生活、扭轉偏差的緊張生活。也就將醣
解能量系統改以粒腺體能量系統為優勢的安心生活，這才是有意義的防癌之道。

而如何才能改變身體的環境呢？除了*飲食*外，就要靠*運動*。

* 運動能讓細胞一直處於高能量狀態

運動的好處有很多，我們可以從三個層面來告訴自己為什麼一定要運動。

1. 運動可以讓我們保持樂觀的態度，提高警覺性、注意力與動力。
2. 運動可以助長神經細胞結合，這是細胞紀錄新資訊的基礎。
3. 運動可以刺激海馬迴中幹細胞內的新神經細胞發展。
4. 運動還可以提振你的心智與體能，並增強你的能量。

當你的壓力愈大，體內的*皮質醇*分泌就會愈多，相對的腦源性神經營養因子
（BDNF）則會愈少，最後大腦就會變成了一個「封閉」的世界。

科學家曾以老鼠實驗，當老鼠的 BDNF 值減少時，便無法從紙袋中找到出口，原
因可能是牠們無法專心思考或沒有精神去探索。然而，運動可以強化腦源性神經
營養因子（BDNF）的生產，提升我們學習、思考與適應周遭環境的基本結構。

身為醫師，當然不會完全不懂這個道理，但卻是在自己罹癌後，才開始正視這件
事，並付諸行動。

* 慢走

骨癌手術後在病床上的那段日子，忍受著身體的劇痛，每天打針、吊點滴、吃藥、
讀書之外，太太每天還要求我陪她出去散步。起初，這件事讓我相當的惱火。我
雖然幸運的不必截肢，但是開刀之後，傷口還未完全復原，走路一拐一拐的，對
重視儀表的我來說，總覺得這樣看起來很醜，很丟臉。但太太不死心，一再要求
我陪她散步。

我沒好氣的回她：「我跛著走路，妳還要我陪妳去散步！」

太太心平氣和的說：「只要能夠讓自己身體好起來，何必在乎別人的眼光？出去
散步也是一種復健，對身體康復很有幫助的。」

我靜下心想想，也有道理，而且我也不希望天天為了這件事和太太嘔氣，所以就
跟著她去散步了。

每天傍晚，只要不下雨，太太便會扶著我在綠蔭樹下，或是河邊小徑慢慢走著，
清風徐來，看綠柳搖曳，聞花香撲鼻，再加上太太溫婉說著許多有趣的故事，我
的心情也跟著開朗起來了。

人的身、心、靈在大自然之中，往往會獲得很好的滋養。這是很奇妙的情境療癒，
也是自然能量匯入人體的作用。

*快樂*的經驗，使我從此養成了每天和太太一起散步的習慣，我們不只一天走幾千
步，後來甚至走到一萬步之遠。
