#+BEGIN_COMMENT
.. title: 水果戰勝癌症
.. slug: fruit-win-cancer
.. date: 2017-08-10 10:24:46 UTC-08:00
.. tags: cancer
.. category: life
.. link:
.. description:
.. type: text
#+END_COMMENT
#+OPTIONS: toc:nil ^:{}
#+LANGUAGE: zh-TW

來源：[[http://health.businessweekly.com.tw/AArticleM.aspx?id=ARTL000093890][20 年戰勝 3 癌！醫師每天早上喝一杯「抗癌五彩蔬果汁」，常保體質弱鹼性]]

+ 人：心臟內科醫師，從小又是運動健將，但罹患癌症，而且還接連三種癌症！巨大細胞癌（骨癌）、腎臟癌與甲狀腺癌。
+ 時：抗癌 20 年
+ 法：CAM 整合療法，
  - 早餐前，我會先喝一杯抗癌蔬果汁
  - 早餐，多半是三明治加牛奶，或是清粥小菜等簡單的食物，常保體質弱鹼性。
  - 鹼性食物多以青菜類為主；酸性食物是魚、肉、蛋和甜食等
  - 不必太過勉強進行全素的飲食。

+ 每天在吃早餐前，我會先喝一杯蔬果汁來增加維他命 C、消化酵素，以及攝取植化素。
  - 所以我並未特別去買有機品，而是換個方式，設法將蔬菜、水果的殘留農藥去掉。
  - 我特別喜歡在黃昏市場採買，而且一定挑當季盛產的蔬果
  - 「抗癌五彩蔬果汁」，組合比例是 3 種蔬菜＋2 種水果，或是 3 種水果＋2 種蔬菜。蔬果種類主要有：花椰菜、高麗菜、蕃茄、蘋果與鳳梨等。

附錄一篇空腹吃水果勝癌症，是從 line 直接轉出，來處不明，全文收錄於後。
重點一句話： *常吃水果，空腹吃*

* 附錄
** 空腹吃水果勝癌症

台大郭銘雄(璁錡)醫師-生死的智慧，演講非常精采

*** 空腹吃水果......(尤其是蘋果)
多虧了有關這個水果和果汁的電子郵件，它告訴了一個治癒癌症的戰略。我的成
功率為 80%。 癌症病人死不了了，不管你信還是不信，治療方法終於找到了。
對那些用常規療法治療癌症而死亡的患者，我深表遺憾。他們中沒幾個存活 5
年, 大多數用常規療法的人僅活兩三年而已。常規療法沒有任何作用，因為不用
常規療法治，病人也活兩三年。癌症病人一旦用了化療或放療，他們的細胞就中
毒了。就衰弱了。癌細胞就會因沒有強壯的抗體而得以迅速擴散。

*** 常吃水果

一說到吃水果，我們就想到把水果 切成塊，大快朵頤。其實，沒那麼簡單。要
講究吃水果的方法和時間。什麼是正確方法呢？千萬別再飯後吃水果，一定要空
腹吃鮮果。這樣水果會起到身體殺毒作用，起到提供身體能量，消肥減瘦作用，
以及參與生化活動的作用。鮮果是重要食物。試想，你在吃兩片麵包後，又吃了
一片水果。本來水果是要透過胃壁進入腸子的，但被食物擋住了。與此同時，胃
發酵，變酸，水果一接觸到它們, 配著胃酸，整個食物就壞了。你會聽到有人抱
怨：我一吃西瓜就愛打嗝兒，我一吃榴槤就脹肚， 我一吃香蕉愛拉稀，等等。
那是因為水果與胃中腐敗的食物混合後產生的氣體造成的。但是你空腹吃水果，
就不會出像上述情況。白頭髮，禿頭謝頂，神經緊張，缺覺黑眼圈，在你空腹吃
鮮果以後，以上症狀一概消失。

郭銘雄(璁錡)博士研究：因所有的水果到了身體變成鹼性，所以像桔子、檸檬這
樣味道酸酸的水果，還是都屬於鹼性食物。只要正確掌握吃水果的時間，你就掌
握了問題的關鍵，讓水果助你美容，長壽，健康，富有活力，幸福和苗條。當你
想喝果汁，就喝鮮果汁，別喝罐裝果汁。也不要將水果或果汁加熱，否則除了味
道尚存，其他所有營養全部流失。 吃完整的水果比喝果汁好。如果非要喝果汁，
那就慢慢地一口一口地喝。讓果汁與唾液充分混合後再咽下。你還可以連續三天
只吃水果不吃它物，這樣你的身體得以清洗，容光煥發，眾人驚喜。

奇異果（獼猴桃）：小而精，富含鉀，鎂。維生素 E，和纖維質。維 C 含量是
桔子的兩倍。

一天一個蘋果，醫生找不到我。蘋果雖含維 C 低， 但它富含抗氧化劑並可提高
維 C 的活性，從而有利於降低結腸癌，心臟病和中風的發病率。

每日吃 2-4 個桔子：可抗感冒。降膽固醇，預防或化解腎結石，降低結腸癌風
險。

西瓜：含水 92%，是解渴最佳食品。所含大量的穀胱甘?能強化免疫系統。還含
有關鍵的番茄紅素，抗癌氧化劑，維 C， 以及鉀。

芭樂和木瓜是維 C 冠軍。芭樂還含有高纖維，能治便秘。木瓜富含糊蘿蔔素，
對眼睛有好處。

飯後喝涼水等於得癌症 。相信嗎？涼水能將剛吸收的油質立刻變成固態，從而
影響消化。固態油脂在酸的作用，變成小碎塊，比固體食物更易於被腸道吸收，
並附著在腸子的內壁。很快形成脂肪，導致癌的生成。所以餐後要喝熱飲。

如果將此文轉發 10 人，你至少救活一人的生命，甚至是你自己。

郭銘雄(璁錡)
