#+BEGIN_COMMENT
.. title: 一天 1 杯黑咖啡，肝癌風險降 42％
.. slug: one-cup-black-coffee-every-day
.. date: 2018-06-22 12:49:57 UTC+08:00
.. tags: coffee, cancer
.. category: life
.. link:
.. description:
.. type: text
#+END_COMMENT
#+OPTIONS: toc:nil num:nil ^:{}
#+LANGUAGE: zh-TW

【原文】[[https://health.businessweekly.com.tw/AArticle.aspx?id=ARTL000095352][一天 1 杯黑咖啡，肝癌風險降 42％！肝臟最喜歡的 10 種食物 - 商業周刊（百大良醫）]]


這篇主要說明的是「促進肝臟健康的十大養分」，咖啡只是其中一項。

* 促進肝臟健康的十大養分

儘管肝臟的健康和整體的飲食型態或三大營養素攝取量息息相關，但其實飲食中的許多微量營養素也是守護或促進肝臟健康的重要養
分，所以不論是奉行地中海飲食、低 GI 飲食或是其他飲食法，都必須多留意這方面。

每一份健康飲食都應該涵蓋這些滋養肝臟的營養素或成分，因為它們不只能保護肝臟不受傷害，讓你擁有健康的肝臟，也能改善非酒精
性脂肪肝的狀況。接下來，我們就來看看這些促進肝臟健康的養分有哪些。

** （一）植化素

這些出現在*水果、蔬菜、堅果和種子*類食物中的植化素，對身體有不少健康功
效，還有機會預防癌症和心臟病等重大疾病的發生。就增進肝臟健康方面來看，
則屬吲哚類（indoles）、茄紅素（lycopene）、木酚素（lignans）、白藜蘆醇
（resveratrol）、花青素（anthocyanin）和槲皮素（quercetin）的效果特別
顯著。

2013 年一篇探討*花青素*對肝臟影響的研究發現，花青素（存在於黑莓、接骨
木莓、覆盆莓、黑葡萄和茄子的表皮）不只能預防肝臟出現脂肪堆積和發炎的狀
況，還能幫助肝臟對抗氧化壓力。槲皮素這種屬於黃酮類（flavonoids）的植化
素，則被發現具有抑制 C 型肝炎感染的功效；*柑橘類、蘋果、洋蔥、巴西里、
橄欖油、葡萄和深色莓果*裡都含有豐富的槲皮素。另外，2015 年中國的研究還
發現，槲皮素能改善因高脂飲食所造成的肝損傷（尤其是脂肪堆積的部分）。

不過，市面上的營養補充劑是不用經過美國食品和藥物管理局檢測和認證的，因
此我*不建議用營養補充劑*來取得這些植化素，直接從新鮮的蔬果中攝取比較健
康。

** （二）咖啡

喜歡喝咖啡的人，如果聽到我接下來要說的事實，肯定會覺得通體舒暢。

研究發現，喝咖啡能降低得到第二型糖尿病、心臟病、中風、膽結石和巴金森氏
症等疾病的風險，而且還可以全面降低早亡的機會。

不僅如此，現在研究還發現咖啡可以降低丙胺酸轉胺脢（ALT）、天門冬胺酸轉
胺酶（AST）和 γ-丙醯基轉肽酶（GGT）的數值；而且就算這些人有慢性肝病或
是過量飲酒、肥胖、抽菸等陋習，咖啡也能發揮一定的功效。另外，連續執行了
四個週期的美國國家健康和營養調查（NHANES）報告顯示，咖啡因的攝取量多寡，
確實和降低非酒精性脂肪肝的風險有相關性（該報告由美國疾病控制與預防中心
的國家衛生統計中心〔National Center for Health Statistics，NCHS〕以問
卷的方式進行飲食攝取量的調查。

2005 年，日本的研究人員在分析了兩場前瞻性世代研究（prospective cohort
study）的成果後發現，咖啡的攝取量和肝癌的得病率呈反比： *與不喝咖啡的
人相比，每天喝一到兩杯咖啡者，其得到肝癌的風險降低了 42％* 。

由於咖啡中含有成千上萬種物質，所以我們不可能直接點名是當中的哪些成分貢
獻了這些護肝功效，因為很可能必須要有多種物質相輔相成（例如當中的強效抗
氧化劑和抗癌物質相互搭配），方能產生這股守護肝臟的力量；不過最近有研究
發現，或許是咖啡中的綠原酸成分所致。不論是飲用*黑咖啡*或是*拿鐵*都可以
獲得這方面的好處，唯一需要注意的一點，就是沖泡咖啡時最好要有*過濾*這道
手續，因為這個動作可以濾除咖啡中大部分的咖啡固醇（cafestol）和咖啡白脂
（kahweol）；這是兩種會讓血中膽固醇含量上升的油性物質。

** （三）ω-3 脂肪酸

*鮭魚、鮪魚、核桃、亞麻籽和奇亞籽*等富含多元不飽和脂肪酸的食物，有助維持心臟、腦部健康和其他身體機能的運作。ω-3 脂肪酸可
改善血脂狀態，並降低造成體內發炎的因素，這些優點都對肝臟健康有正面影響。事實上，奧勒岡州立大學新發表的研究發現，屬於
ω-3 脂肪酸一員的 DHA（docosahexaenoic acid，二十二碳六烯酸）能預防脂肪肝，且成效顯著。

此外，研究還顯示血液中缺乏 ω-3 脂肪酸是造成非酒精性脂肪肝惡化的直接因素之一。

** （四）纖維素

纖維素有兩大類，分別為*水溶性*和*非水溶性*；對身體健康來說，它們各有各有的好處。

*水溶性纖維*有助降低體內膽固醇的含量和整體心臟病的風險，同時它也是維持
腸道健康的一項重要因素；富含水溶性纖維的食物泡在水裡體積會膨大，

例如*燕麥、豆類和奇亞籽*等。

*非水溶性纖維*的食物有：*堅果、麩皮、糙米、水果的表皮*等；這兩種纖維素
都有益肝臟健康。

2007 年*巴西*的研究發現，非酒精性脂肪肝的人連續 3 個月，每天食用 10 公
克的水溶性纖維（以營養補充劑的形式攝取）後，他們上升的肝指數下降了，
BMI、腰圍、胰島素阻抗和膽固醇也有顯著改善。

研究也發現，攝取充足的*膳食纖維*能降低第二型糖尿病（包括胰島素阻抗）的
風險、膽固醇和三酸甘油酯的含量，並讓體重獲得比較好的控制—這所有的改變
都有助於降低得到肝臟疾病的風險。

** （五）益生菌

好菌是讓我們擁有一副健康腸道的關鍵角色，健康的腸道可以為肝臟的健康帶來
保障，因為腸道和肝臟之間的互動密切，就如我們在前面提到的，部分學者甚至
創了一個「腸肝軸系」的名詞，來描述腸道菌相可能透過怎樣的機制來保護肝臟
不受慢性損傷的迫害。

其實不少研究都已經發現非酒精性脂肪肝、肝硬化或酒精性肝病的病人，其體內
的腸道菌相都出現了轉變。好消息是，

有研究認為，只要透過食用*益生菌*（促進腸道健康的好菌）和*益生質*（人體
不能消化的纖維素，但卻可以做為益生菌生長的養分）重新打造出擁有健康菌相
的腸道

為了讓我們的腸道*好菌*多多，可多食用*優格*、*優酪乳*、*味噌*、*泡菜*、
*天貝*（一種印尼的發酵豆製品）和*酸菜*等發酵食品，或直接服用*益生菌營
養補充劑*，保持腸道菌相的健康。

提升腸胃功能，而且增進了肝臟的機能

** （六）大豆蛋白

大豆常常因為它含有雌激素的特性身負惡名，但其實富含天然*大豆蛋白*（非大
豆加工製品）的飲食，對健康有諸多幫助，肝臟也是受惠者之一。研究發現大豆
裡的*異黃酮*能透過調節肝臟的脂肪代謝和改變肝臟的基因表現，來提升肝臟氧
化脂肪酸的能力，進而減少脂肪囤積在肝臟的機會，達到預防或治療非酒精性脂
肪肝的效果。

另外，*大豆異黃酮*亦具有降低發炎因素和改善葡萄糖耐受度的能力。

獲取大豆蛋白的最佳來源是由完整大豆製成的食品，例如*豆腐*、*毛豆*、*天
貝*和*味噌*都是很好的選擇，而非成分中徒有大豆分離蛋白的脆餅或能量棒。

** （七）辛香料

在料理中添加辛香料，除了可以增加味蕾的豐富性，*薑黃、咖哩粉、辣椒、薑*
和*葫蘆巴籽*裡的活性成分也能促進肝臟的健康。

大部分辛香料的護肝功效都是源自於它們所含的*抗氧化物質*，不過也有少部分
的辛香料是因為擁有抗發炎、改變基因表現或是增進解毒酵素活性的成分。

以 2014 年 7 月發表在期刊《消化學》（Gut）的一篇研究為例，他們在實驗過
程中發現薑黃裡的薑黃素（curcumin）能阻擋 C 型肝炎的病毒進入肝臟細胞；

2013 年，中國也同樣在實驗時發現*薑黃素能阻止肝癌細胞生長*。

2013 年來自台灣的研究團隊則發現，萃取自薑的精油有助於對抗酒精性肝病，
因為他們每天餵食患有酒精性肝病的小老鼠薑精油後，小老鼠的肝臟便不再受到
損傷。

在*葫蘆巴籽*方面，2011 年日本研究發現，當大老鼠採取高油、高糖飲食
時，若攝取葫蘆巴籽將能抑制脂肪在肝臟堆積。

** （八）綠茶

儘管常被用來當成減肥聖品的濃縮綠茶萃取錠劑有礙健康（因為*大量服用很可
能會導致急性肝衰竭*），但*適度飲用綠茶*卻有益肝臟健康。

這項優點很可能是*綠茶多酚*的功勞，因為研究已經證實綠茶多酚能降低 DNA
受損機率和血脂濃度。

不過想要安全無虞的獲得綠茶的好處，我的建議是不要攝取任何營養補充劑形式
的綠茶萃取物，要*飲用天然的綠茶飲品，不論是冷泡或熱水沖泡的綠茶*。

** （九）維生素 E

研究認為，維生素 E 有助降低升高的肝指數、預防非酒精性脂肪肝惡化，並減少
疤痕組織在肝臟生成的機會。

就跟前面介紹的幾項護肝養分相同，最好的維生素 E 也是來自食物，而非營養
補充劑；富含維生素 E 的食物有：*植物油*、*堅果*、*種子*、*全穀類*和*蛋
*等食物。

維生素 E 並非多多益善，*過量攝取維生素 E 反而會對健康造成反效果*

** （十）膽鹼

膽鹼屬於*維生素 B* 的一員，是維持人體正常生理作用不可或缺的元素

許多與肝臟有關的代謝作用都需要它的參與才可以進行，極低密
度脂蛋白（VLDL，三酸甘油酯從肝臟被分泌出的形式）的代謝就是一例。萬一體內膽鹼的濃度過低，就會造成脂肪堆積在肝臟，進一步
導致粒線體的功能損傷、脂肪酸氧化能力下降和腸道菌相變差等不利健康的生理變化，這簡直是牽一髮而動全身的骨牌效應。

不少研究發現，*膽鹼缺乏*可能會促進非酒精性脂肪肝和肝癌的生成，然而體內
膽鹼含量較高時，卻可能具有預防這兩類肝臟疾病的能力。

富含膽鹼的食物有：*蛋品*、*貝類*、*禽肉*、*花生*、*小麥胚芽*和*全大豆製品*。

* 結語
只要你的飲食主要以*全穀類*、*蔬菜*、*水果*、*豆類*、*堅果*和*健康的油脂*（例如橄欖油）組成，並搭配小
分量的*乳製品*、*魚類*和*海鮮*，紅肉則偶爾少量食用，便可充分掌握獲取最佳健康
和護肝飲食的重點。
