#+BEGIN_COMMENT
.. title: Post-installation of Archlinux
.. slug: post-installation-of-archlinux
.. date: 2017-11-26 23:28:36 UTC-08:00
.. tags: linux, haskell, xmonad, taffybar
.. category: computer
.. link:
.. description:
.. type: text
#+END_COMMENT

首先依 [[../install-arch-linux-2017][Install Arch linux (2017)]] 將基本系統裝好，接著參考 [[https://wiki.archlinux.org/index.php/General_recommendations][General
recommendations - ArchWiki]] 記錄下對我而言必要的軟體及簡單設定，讓日常
進入可工作狀態。

* haskell
安裝的方法參看 [[../install-haskell-applications][Install Haskell Applications]]

* 桌面及外觀

** theme

#+BEGIN_SRC sh
yaourt -S breeze{,-kde4,-gtk} flat-remix-git lxappearance
#+END_SRC

Using Breeze theme and Flat Remix icon theme

** lxappearance

用 lxappearance 修改 gtk 程式的外觀。

尤其是 google chrome 書籤列的字體，可能太小。這時即可用 lxappearance 調整
字型和大小。

** oblogout and screen lock

https://wiki.archlinux.org/index.php/Oblogout

oblogout is an optional, configurable logout script that presents a
graphical interface (i.e. buttons) to cancel, logout, restart,
shutdown, suspend, hibernate, and lock the screen.

#+BEGIN_SRC sh
yaourt -S oblogout

sudo nano /etc/oblogout.conf
#+END_SRC

修改 [looks] 中的 buttons，以顯示按鈕。

#+BEGIN_EXAMPLE
[looks]
buttons = cancel, restart, shutdown, lock
#+END_EXAMPLE

修改 [shortcuts] 中不用的命令刪掉。

#+BEGIN_EXAMPLE
[shortcuts]
cancel = Escape
shutdown = S
restart = R
#suspend = U
#logout = L
lock = K
#hibernate = H
#+END_EXAMPLE

修改 [commands] 中的命令。

#+BEGIN_EXAMPLE
[commands]
lock = slock
#+END_EXAMPLE

* system
DPMS: display power manpage system
slock:

* 網路
** dropbox
dropbox 在 archlinux.fr 中

#+BEGIN_SRC sh
yaourt -S dropbox perl-file-mimeinfo
#+END_SRC

** qbittorrent
#+BEGIN_SRC sh
yaourt -S qbittorrent
#+END_SRC

* 檔案管理
using mc and pcmanfm-qt

#+BEGIN_SRC sh
yaourt -S mc pcmanfm-qt gvfs-mtp
#+END_SRC


** pcmanfm-qt

使用 pcmanfm-qt, for mtp 傳送檔案 and dropbox

*** issues

error message:

#+BEGIN_EXAMPLE
/usr/bin/xdg-open: line 922: pcmanfm: command not found
#+END_EXAMPLE

fix this problem:

#+BEGIN_SRC sh
sudo ln -s /usr/bin/pcmanfm-qt /usr/bin/pcmanfm
#+END_SRC

** mc

* 影音
#+BEGIN_SRC sh
yaourt -S alsa-utils mpd mpc ncmpcpp mpv ffmpeg sox kodi kid3 aegisub
#+END_SRC

** alsa
聲音

** mpd, mpc, ncmpcpp
音樂背景播放

** mpv
影片播放

#+BEGIN_SRC sh
mpv cdda://
mpv dvd://
#+END_SRC

** kodi
影片管理

** aegisub
字幕處理

** ffmpeg
影片處理
2-pass to control file size

** dvdbackup
** sox
wav 轉 aiff

** kid3
音檔加 tag

* 其它工具
** emacs
ripgrep
opencc: using s2twp.json

** meld
#+BEGIN_SRC sh
yaourt -S meld
#+END_SRC

** albert
應用程式快速啓動器

#+BEGIN_SRC sh
 yaourt -S albert qt5-graphicaleffects qt5-quickcontrols
#+END_SRC

** speedcrunch (calculator)

#+BEGIN_SRC sh
yaourt -S speedcrunch
#+END_SRC

** calibre
管理電子書，我只用來管理我的 kindle

#+BEGIN_SRC sh
yaourt -S calibre
#+END_SRC
** nikola
#+BEGIN_SRC sh
pip install nikola Pygments
#+END_SRC

** htop
** gnash

#+BEGIN_SRC sh
yaourt -S gnash-git
#+END_SRC

可讀 .swf 檔

* stock
** python and depending modules

#+BEGIN_SRC bash
yaourt -S python python-pip
#+END_SRC

** systemd timers
