#+BEGIN_COMMENT
.. title: 鄭曼青師徒對話錄
.. slug: master-zheng-and-student-smith
.. date: 2018-06-21 11:17:46 UTC+08:00
.. status: draft
.. tags: tai-ji
.. category: life
.. link:
.. description:
.. type: text
#+END_COMMENT
#+OPTIONS: toc:nil ^:{}
#+LANGUAGE: zh-TW

轉錄自[[https://m.facebook.com/story.php?story_fbid=466445743807976&id=100013276627941][太极亚洲]]

史密施先生，美國人，1959 年起隨鄭曼青大師學習太極拳，此後勤練此拳並教
授此拳至今。他認為太極拳帶給他一個謙和的自我和健康的體格。

本文是史密施先生與鄭曼青大師合著之《太極》一書中所選出的一節師徒對話。

* 引言

我們坐在那裡，大師微笑著。有人告訴我，當他心情合適時，會有問必答，他說：
“如果你以小卵石撞鐘，鐘聲必小。如果你以大木槌擊之，則其聲必大。同樣的，
如果你問我大問題，答案也必重要。”這話使我得知應從何處著手。於是我問：

史：

在大部分武藝行中，學生的造詣均會接近老師，或高過老師。何故你的學生沒有
能接近你，不管他們進步如何快速，其水準均低你遠甚。可有何祕訣？

鄭：

不錯，是有祕訣。但是此祕訣太過簡單，簡單的幾乎令人不敢相信。但是你又
非信不可。否則你就無法成功。

其祕訣僅為：你必須*身心放鬆* ，你必須長時間*接受失敗* 。你必須投資於
失敗，否則你就無法成功。

我有如今的成就，是因我把驕傲置之於一旁，相信我老師的話，把身體放鬆，心
靈靜定，只*讓氣隨意行* 。開始時常使我遍體受傷。有時我會被重擊而跌至失
去知覺。但仍堅持下去。聽老師的話，注意我的氣。在慘敗時我會忘了驕傲、焦
慮以及自我。把自己身心完全騰空而全部讓位於氣，漸漸的我的技術進步了。直
到這時我的反應才變得靈敏。可使化與打於瞬間完成。我的學生或是不相信這一
套，或是雖相信而不熱心追求，何能得成。

史：

你講起來很容易，如果心意正確，身體放鬆就有進步，但是，如無辛苦的鍛鍊、
規律的練習並不斷地努力，是否可以？

鄭：

如想精通此藝，必須求助於你剛才所提各項。你須辛勤努力，每日不斷，但是卻
須注意不要把太極拳與少林拳混為一談。

後者注重鍛鍊肌肉及力氣，而練太極拳，心中常須念記拳經各論。並非要你每天
苦練一、二小時就必能成，練習必須得法，否則全為白費。

吾師楊公澄甫是由其著名的父親楊健侯所親授。三十歲時任教於山東某富宦之府
內。其處生活優裕，其人也就變得肥胖及懶散，此後他還返北京，生活實形放蕩。
其父得知此情，令其辭職逐裡，將其禁閉於一空屋內，不准他與任何外界人物接
觸，前後四年之間，除了他父親每天來與他練拳，推手，同時也練練太極器械外，
不准任何人去看他，在這期間他的成就遠超過前此他的一生所學。四年後他走出
囚室，便可輕易地打敗他父親最好的徒弟。前此他經常是他們手下的敗將，如今
他已是一位偉大的拳手，其偉大終身與共。此後多年間，雖然他不須多加練習，
亦能可保持其效能。

這是太極拳的一項必然特性，一個人如果不斷地進步，將可達到一種程度，此後
即不必要練習，因其已臻化境。對此我不再多談。

史：

在練拳的時候怎麼能知道是不是已鬆？

鄭：

知不知道是主觀的，而鬆不鬆是客觀的。我願意說，當一個人在練習整套拳架的
過程中，其心靈完全不受外界的干擾，這便是求鬆的一個好的開始，但是這只是
第一步。

下一步是你須踏踏實實的練。練完時你會*筋疲力盡* 。當你的雙肩覺得沉重時，你
就知道這已是接近真鬆了。這是“陸地游泳”的結果。

史：

但是拳經不是告訴我們，你的身體必需如此輕靈，一羽相加都可以覺得。你怎樣
把這種輕靈與假設的抵抗而來的筋疲力盡相提並論呢？

鄭：

這是不相稱時。雖然聽起來有此矛盾。你當然可以輕鬆愉快的練五分鐘的拳架而
毫無倦意。這卻無助於你求鬆。你打拳時慢而正確，假設前有抵抗，你必會疲倦。
但是在真正交手時，你的身體擺脫了你心中的抵抗的束縛，就會覺得無比的輕靈
及敏捷。

史：

如你所知，我曾跟過其他數位老師學習太極拳。我不是對你不敬。但因為我們的
時間都很有限，我又想寫些有關太極拳的書，我想是最好能儘量的學。其他各派
大部分都加輔助的運動以增強其呼吸、活力及拳藝。你看這種運動是否有益？

鄭：

只有小氣的老師才會嫉妒學生到別處學藝。我非常高興你能從各派去嘗試。因為
我知道你必會發現，在這種拳中你將只有一位老師。拳架本身已是變化多端包羅
圓滿非常有益。附加的運動只會使你分心，妨礙進步。

史：

少林拳是否是一種非常好的健身運動及防身武術？

鄭：

如果我認為是的話，我會取少林而捨太極。在運動方面來說，他注重肌肉的緊張
及蠻力而不注意健康。在搏鬥時，因為你永不會超出依靠力氣及技巧的範圍，因
此也就不會得到真正的優勢。我不是自誇。當我年輕在大陸時，常遇各派人氏的
挑戰，吾藝從未敗過。

史：

推手的重要性如何？

鄭：

非常重要，不經推手，你就不會有進步。但是注意，我現在告訴你，你最好與一
*小孩*相推。同一有技巧的大人相推他會用力，你也就會跟著用力。與小孩相推時
把他看作是大人。與大人相推把他看作是小孩。這話聽起來矛盾其實並不。小孩
會提供你一個*鬆*的練習夥伴。

當你從他“可鬆性”中獲益時，你可把他看作與你相同，假裝他是大人。這就把
練習提升“用”的方面來。現在反過來講。為什麼要把大人看作是小孩呢？這只
是一種輕視的方法，以使我們卻除怕意，但這亦不意味這種“勇氣”可以真的戰
勝怕懼。我們在卻除懼怕時也去掉傲氣。

史：

在推手時，如讓對手接觸到自己身體，是否危險？在真正交手時，這種情形是否會慘敗？

鄭：

推手主要是一種達到目的方法。他教觸覺的靈敏及辨別的能力 (意即聽勁及種
勁——譯者注)，也教你對於距離的審忖。在真正交手時不要讓敵手觸控到你。
但是卻要儘量的靠近他以利攻擊。有些大師們具有我們所說的接勁。這種勁不但
可以收化敵人的攻擊，在同時也予以反擊。有些更高的大師們的這種能力是由潛
意識所控制。你如從後向他攻擊，他可借敵人之力將其反彈出一丈以外。而自己
幾乎並不覺得。這種人在真正交手時自無困難。一般的拳手雖無此種能力，但可
經由推手鍛鍊其知覺，使其可以*接近敵人而不讓敵人觸控到自己* 。

史：

莊子說：醉漢無傷，其魂固也。這種狀況是否是太極拳所追求的呢？如果莊子所
言不假，那麼我們只要變成酒鬼不更簡單嗎？

鄭：

把自己騰空是為了克服恐懼，這是“無為”的主要目的之一。這也是所以道士之
將死，可生起烈火，從容走入之道理。(在這裡我說，這種不怕死的品性，並非
中國所專有。日本的武士亦求死的美。更不須提聖勞倫斯，在其身受炮烙時對其
行刑者說：“把我翻個身吧，這半邊已烤好了”)

大師微笑著表示欣賞，繼續說：“不錯，醉漢是解除了顧及。他的肌肉不緊張，
他的身體鬆弛。但是並非完全如此，因為醉漢總是會認路回家。醉漢失去了心意，
為環境所左右。反過來在太極拳，我們雖然放鬆了身體，但卻保持一顆靈活清醒
的心。”

史：

為什麼楊澄甫不到西方教拳？

鄭：

曾有一中醫生從美國回到廣州，他遊說楊氏同他返美，說是可賺大錢，被其所拒。
西方及金錢對楊氏均不具吸引力。他對其所屬環境非常滿意，不思改變。

轉自網路中和國術館
