#+BEGIN_COMMENT
.. title: [LINE] 走路吧！
.. slug: walking
.. date: 2018-05-22 12:36:56 UTC+08:00
.. tags: health, walking
.. category: life
.. link:
.. description:
.. type: text
#+END_COMMENT
#+OPTIONS: toc:nil ^:{}

轉錄自 LINE

走路吧！

孫正春走到腫瘤也怕他！
孫正春身體力行 100 天，2 個腫瘤消失了 16 種宿疾改善了！想健康，走路最簡單，不花錢，絕無副作用！

「我覺得爸爸會抗癌成功，關鍵在於『堅持到底』。他的確在開始長途走路的一
百天內腫瘤消失了，心跳正常了，很多人看到成效出現就停止，但他非但沒有鬆
懈，反而更堅持走下去，直到現在，持續二十幾年。」

孫羽佑，孫正春之子，神經科學博士

他原本天天吃焢肉、能坐就不願站，直到癌症的陰影迫近，才驚覺必須改變！

從完全不走路到一天走上六小時，他慢慢走，打赤腳走，拿著啞鈴負重走；他吃
樹葉、喝葉子水，打造了一個「山上的家」三餐吃優格，徹底地改變了體質。
兩個腫瘤一百天消失不是奇蹟，而是「動、綠、奶」的有力實踐。

他到宜蘭工作，就把走路的觀念傳給同事；搬回埔里，帶動了遠近馳名的社區
「夜走」熱。

他還鼓勵原已無法進食、無法行動的癌末朋友，從吃一小滴優格、爬行一小步開
始，重獲健康。

這一份對走路的執著和熱愛，鼓舞了無數人迎向希望。

他曾花六天翻越中央山脈，從南投走到宜蘭；四十五天健走，以一雙傷痕累累的
「真皮鞋」實現赤腳環台夢想；更跨足世界，走向義大利，兩天完攻山海雙線的
考驗。

他賦予了「距離」全新的意義，只要走路到得了的地方，就不算遠。人生的路，
原來可以靠雙腳走出來，而最重要的是：堅持走下去。「堅持到底」，讓孫正春
贏回健康，更讓他走出了康莊大道！

台灣國家衛生研究院：每日健走 15 分鐘，延壽 3 年！英國癌症團體：每日健
走 20 分鐘，癌症死亡率減半！

走路的好處，他們都親身體會到！

◎孫正春之妻陳梅香曾患腎臟病，身體水腫到像懷孕，每天走路讓她重獲健康。

◎紀政的尿失禁毛病因走路不藥而癒，而且 6 個月瘦了 20 公斤。

◎希望基金會祕書長黃純湘的癌末父親，靠走路贏回了 7 年人生。

◎前暨南大學公共行政系教授梁雙蓮，以走路擺脫了更年期及失眠困擾。

◎作家陳芸英長期受便祕所苦，開始走路的第二天，便祕問題竟然解決 了。

走路很簡單，就是「走出去」而已。出門多走一站搭車或提早一站下車；在公司
少打一通電話，直接走去找同事；不必刻意挑什麼健走路線，有時間就走。

把自己交給雙腳，慢慢走，不要急，才能走得遠、走得久。有人問： 「走這麼
長、這麼久的路，不累嗎？」孫正春說： 「只要心不趕，就不會累。」

◎不管身體有多糟糕，背一定要挺，不能垮下去，只要能動就要動，動一 下也
好。可別小看「動一下」這是很單純的求生訊號。

◎既然站得起來，就試著走出去吧！一步就好。第二天再走一步，慢慢來，只
要 一天進步一點點就可以。

◎「走路」就像每天都要吃飯、睡覺一樣，是生命的必需品。讓走路融入每日
生活，養成隨時走路的習慣。

◎走路是最緩和、最舒服的一種運動，隨時隨地都可以進行，不需要技術、不
需要夥伴。

◎其實走路很簡單，就是走出去而已，把自己交給雙腳，慢慢走，不要想太多，重點是持之以恆。

◎剛走路的人都希望走快點，趕快走完，好回家休息，但當你走到一個程度，就會曉得什麼樣的方式對你的身體和生理有幫助。

走路運動....不是趕路運動。
輕鬆走，慢慢走；
天熱/帶條毛巾；
天涼/帶件薄外套。

生病不是意外，是自己平常不注意自己的身體健康。病痛來襲，只有默默承受。

走路可以運動到環跳穴，改善上熱下寒的情形，也可以活潑足三陽的氣機，使陽下行而陰上滋，是活命之源！

⭕⭕ 榮總急診部王醫師傳送 @ 很寶貴的養生短文
◎成為永遠病人的二大原因：過食+藥物！

就是吃太多啦，還有就是吃葯，這絕對不是好事，醫師和護理人員，都很少吃葯。

◎糖尿病是全身性的代謝紊亂！主因則是胰臟過度疲勞！

◎細嚼慢嚥是在降低胰臟負擔！

◎活得健康的重要原則？一少三多！
A. 少吃；
B. 多休息
C. 多喝水；
D. 多流汗！

◎滿身流汗對各種疾病都是有益的！

◎飯量越大丶耗氧也越大丶細胞越缺氧，心臟就越加壓，血壓也就越高了！

◎吃飯最好＂五分飽＂，不要撐飽！

◎當身體飢餓感訊號出現時，正是排毒旺盛，免疫功能快速增強時！

◎空腹時身體發熱流汗是最有效的新陳代謝法，也是細胞自行清血解毒，補氣活化的時機！（消化系統運作時，就停止排毒！）

◎癌症的主因：超級中毒＋組織缺氧（重度缺氧）！

◎癌症是身體長期處於中毒狀態（強酸），所引起＂缺氧＂的自然現象！

◎＂氧＂是身體治病救命的靈丹，它決定腺體調節能力，免疫系統的強弱，更掌控了癌症病人的生殺大權！
