#+BEGIN_COMMENT
.. title: 部落格，重回 nikola+org-mode
.. slug: zhong-hui-nikola-xie-luo-ge
.. date: 2018-05-14 09:32:19 UTC+08:00
.. tags: linux, nikola
.. category: computer
.. link:
.. description: writing blogger using by nikola again.
.. type: text
#+END_COMMENT
#+LANGUAGE: zh-TW
#+OPTIONS: toc:3 num:t ^:{}

掙扎了許久，還是先用 [[https://getnikola.com/][nikola]] 記錄一些事，畢竟比較熟悉，能快一點上手。

* 安裝
#+BEGIN_SRC sh
pip nikola
#+END_SRC

* 設定

執行 ~nikola init~ 後，依指示設定，比較省事。

#+BEGIN_SRC sh
nikola init <blog-name>
cd <blog-name>
#+END_SRC

** configuration file
修改 ~conf.py~ ，慢慢改，內容很多，不必急於一時。

** theme
#+BEGIN_SRC sh
nikola theme install bootstrap
#+END_SRC

** org-mod
先安裝 plugin orgmode，再做一點點微調即可。

#+BEGIN_SRC sh
nikola plugin -i orgmode
#+END_SRC

開啟 ~<blog-name>/plugins/orgmode/init.el~ ，加上以下的程式碼。

*** 刪除不必要的空白

換行時，在兩個中文字間會有一個空白，不好看，所以想辦法刪除。

#+BEGIN_SRC emacs-lisp
  ;; https://coldnew.github.io/a1ed40e3/
  (defadvice org-html-paragraph (before org-html-paragraph-advice
                                        (paragraph contents info) activate)
    "Join consecutive Chinese lines into a single long line without
  unwanted space when exporting org-mode to html."
    (let* ((origin-contents (ad-get-arg 1))
           (fix-regexp "[[:multibyte:]]")
           (fixed-contents
            (replace-regexp-in-string
             (concat
              "\\(" fix-regexp "\\) *\n *\\(" fix-regexp "\\)") "\\1\\2" origin-contents)))

      (ad-set-arg 1 fixed-contents)))
#+END_SRC

*** Convert inline verbatim to kbd when HTML export

ref: https://emacs-china.org/t/org-mode/1165

change =verbatim= to =kbd=

~code~

#+BEGIN_SRC emacs-lisp
  (setq org-html-text-markup-alist
        '((bold . "<b>%s</b>")
          (code . "<code>%s</code>")
          (italic . "<i>%s</i>")
          (strike-through . "<del>%s</del>")
          (underline . "<span class=\"underline\">%s</span>")
          (verbatim . "<kbd>%s</kbd>")))
#+END_SRC

*** 用 pygment 幫程式碼著色

#+BEGIN_SRC sh
$ cd themes/your-theme-name/assets/css
$ pygmentize -S emacs -a .highlight -f html > pygment.css
#+END_SRC

** 用 ~nikola github_deploy~ 快速發佈文章

REF: https://getnikola.com/handbook.html#deploying-to-github

*** Initialize a Nikola site, if you haven’t already.

*** Initialize a git repository in your Nikola source directory by running:

#+BEGIN_SRC sh
git init .
git remote add origin git@github.com:user/user.github.io
#+END_SRC

url 要確認清楚，必須是 ssh 形式的，未來才可不必一直重覆輸入密碼

*** Setup branches and remotes in ~conf.py~:

- GITHUB_DEPLOY_BRANCH is the branch where Nikola-generated HTML files
  will be deployed. It should be gh-pages for project pages and master
  for user pages (*user.github.io*).

- GITHUB_SOURCE_BRANCH is the branch where your Nikola site source
  will be deployed. We recommend and default to *src*.

- GITHUB_REMOTE_NAME is the remote to which changes are pushed.

- GITHUB_COMMIT_SOURCE controls whether or not the source branch is
  automatically committed to and pushed. We recommend setting it to
  *True*, unless you are automating builds with Travis CI.

*** Create a ~.gitignore~ file. We recommend adding at least the following entries:

#+BEGIN_SRC sh
cache
.doit.db
__pycache__
output
#+END_SRC

If you set GITHUB_COMMIT_SOURCE to *False*, you must switch to your
source branch and commit to it. Otherwise, this is done for you.

*** Run ~nikola github_deploy~.
This will *build* the site, *commit* the output folder to your deploy
branch, and *push* to GitHub.  Your website should be up and running
within a few minutes.

*** 在 nikola github_deploy 之前
為了要能用 ~nikola github_deploy~ 指令，有以下的準備工作：

**** install ghp_import2

#+BEGIN_SRC sh
sudo pip install ghp_import2
#+END_SRC

**** install and setup ssh
為了不必一直重覆輸入 github 的帳密，可用 ssh 解決。

***** install openssh

#+BEGIN_SRC sh
yaourt -S openssh
#+END_SRC

***** follow github help page to add ssh connect to github
- [[https://help.github.com/articles/generating-a-new-ssh-key-and-adding-it-to-the-ssh-agent/][Generating a new SSH key and adding it to the ssh-agent - User Documentation]]
- [[https://help.github.com/articles/working-with-ssh-key-passphrases/][Working with SSH key passphrases - User Documentation]]
- [[https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/][Adding a new SSH key to your GitHub account - User Documentation]]

****** 產生 ssh key
#+BEGIN_SRC sh
ssh-keygen -t rsa -b 4096 -C "your_email@example.com"
#+END_SRC

螢幕上會出現
#+BEGIN_SRC sh
Enter passphrase for key '/home/USERNAME/.ssh/id_rsa'
#+END_SRC

此時不要輸入密碼，直接按 =Enter= ，否則未來 ~nikola github_deploy~ 時，
就要每次輸入密碼。

****** 將 ssh key 加到 github 中
依 [[https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/][Adding a new SSH key to your GitHub account - User Documentation]] 執行

**** 確定以 ssh 連上 github (不能是 https)

#+BEGIN_SRC sh
$ git remote -v
origin  git@github.com:mariolong/mariolong.github.io (fetch)
origin  git@github.com:mariolong/mariolong.github.io (push)
#+END_SRC

如果不是，要用以下指令修正。

#+BEGIN_SRC sh
git remote set-url origin git@github.com:mariolong/mariolong.github.io
#+END_SRC

* 開始使用

建立新的文章，

#+BEGIN_SRC sh
nikola new-post -e -f orgmod
#+END_SRC

寫完就 build

#+BEGIN_SRC sh
nikola build
#+END_SRC

或發佈吧！

#+BEGIN_SRC sh
nikola github_deploy
#+END_SRC

一切都就緒了，那就開始專心寫文章吧！
