#+BEGIN_COMMENT
.. title: 鼻咽癌放療記錄
.. date: 2017-07-29 09:29:00
.. updated: 2017-08-09 14:00
.. comments: true
.. tags: 癌
.. layout: post
.. categories: health
.. permalink:
.. options: toc:nil ^:{}
#+END_COMMENT

* 前言

如果不是頸部腫瘤在 2017/2/28 突然惡化、長大，我應該還是不會給西醫治療。

在放療前，對它真的很排斥，因為它的傷害是永久性的，能不能回復還是未定之
數，因此不願意去做放療。但是，當時也沒有好的方法能讓腫瘤消退，只好去急
診，尋求西醫的協助。既然已經決定用西醫療法，只能想辦法將副作用降至最低。

這次療程共 35 次放療，加上每週一次，共 7 次的化療。我盡量記錄有何不適
和我的解法，希望對要放療的人有點幫助。

* 放療副作用

- 口 :: 口破，舌頭破，口乾。
- 鼻 :: 流鼻血，第 22 天開始，大約第 60 天狀況大約解除，持續約 40 天。
- 頸 :: 皮膚黑、破，脖子變硬。皮膚破的狀況約從第 40 天到第 66 天，持續約 26 天。
- 耳 :: 耳鳴，聽力變差。
- 眼 :: 複視。

* 營(保)養品

因為放療會有以上的副作用，希望能有一些東西幫忙，讓傷害降到最低。

** 麩醯胺酸

補充修補時需要的營養和熱量。

沒有放、化療時吃 15 克，有放、化療時吃 30 克，要吃到舌頭破的狀況消除。
我買的是 1 包 15 克，很好計算每天的量。總共吃了  天，  包。

** 安素、倍力素、倍速

如果吃不下或插鼻胃管時，灌食、補充熱量用。

開始吃的時候，每天只喝 2 瓶，早晚各一瓶倍力素或倍速。等到療程結束時，
第 50 天，口腔、舌頭突然很痛，整天只能喝安素、倍力素、倍速，這時消耗得
很快，每天要 6~8 瓶，大約也要 2 星期，等待修復。後來大約 1 天喝 4 瓶，
習慣早晚各一瓶倍力素或倍速。總共喝了 200 瓶以上。

** 蘆薈、保濕面膜、NS-21

只用蘆薈、保濕面膜應該不夠，可能還是要早一點用 NS-21，但很貴，1 支
1200 元。不過，我是不會知道效果如何，等到破皮才用，肯定是來不及啦！或
許該先和醫生談有沒有好用的產品，不要等到破皮了才擦藥。

* 作息，飲食

和徐醫生談過後，清楚知道，放療的傷害還是要靠自己修復，多吃營養，體重要保
持住，不能不降太多，如果體重下降超過 5 公斤，要插鼻胃管餵食。這是西醫
的作法。

靠自己修復？那就是要加強免疫力囉！不外乎營養、運動、休息、心情。

運動、休息、心情，就不說了，這是一定要做的事。營養就比較麻煩，要吃的東
西真多啊。

多吃高蛋白，麩醯胺酸，以補充修補時需要的營養和熱量。

維生素 C 可有效抗癌，所以多吃水果，芭樂，香吉士，奇異果，百香果。

西醫開了許多藥，主要是消炎止痛，原因是怕口腔疼痛影響進食，體力衰退，體
重持續下降。

我是不會只用西醫的方法，另外，還去看了許中華中醫師，用中醫調理身體。許
中華醫生很有名，主要是調我的腸胃，腸胃好，身體不會老。許中華醫生的藥真
的有效。

一天的要吃的東西大略如下：

- 06:30 :: 安素，麩醯胺酸，早上西藥，起床後先吃。然後吃早餐：水果，蛋，
           地瓜、麵或粥。7 月份開始加上「有機高纖高鈣亞麻多穀奶」補充
           維生素、礦物質。8 月早上加上有愛心蔬果汁喝。

- 07:30 :: 吃許中華醫師的中藥，調養身體。

- 12:00 :: 午餐基本上吃麵，方便就好。飯後吃中藥。

- 18:00 :: 安素，麩醯胺酸，晚上西藥，然後吃晚餐。

- 20:00 :: 吃中藥

- 22:00 :: 上床睡覺

* 運動

能做的運動太多了，馬克「抗癌氣血本功」就不錯，陸文灝暖身操，拉筋功，太極拳，內功，
苦行脊椎歸位操，有空就做，好好調炁。

爬山，是一定要的啦。

7/10 開始，每天從醫院走路回家，大約 40 分鐘，愈走身體愈好。

* 總結

放療過程中的副作用，我覺得最嚴重的是：
1. 嘴破、舌頭破、喉嚨痛
2. 脖子燒得黑黑，甚至於破皮
3. 口乾，上顎痛

尤其是嘴破喉嚨痛真的很困擾，不止影響食欲也影響了心情。因應嘴破喉嚨痛，
我用了：
- 「必達定」嗽口水，因為會痛，所以沒用幾次。
- 「白樂汀口腔凝膠」，效果還不錯，可以舒緩口乾狀況。
- 「椰子油」，經實證，用椰子油漱口，有時可緩解疼痛感。
- 「滅菌靈」，徐醫生開來治療「白色念珠菌」的藥，殺菌也應有幫助。
- 「口內膏」，謝醫生開來治舌頭破的藥。

反正, 我是全用上了，但也只能緩解，並不能完全不痛。只能多喝水，等它自己痊癒。

脖子燒得黑黑、破皮。一開始是用蘆薈凝膠和面膜保養，後來發現脖子還是會變
黑。等到 7/14 脖子有點痛才買 NS-21，這時已經來不及，脖子開始破皮了，要
花更多的力氣和時間處理。7/20 使用徐醫生開的「燙膚舒」，疼痛的狀況有緩
解，皮膚還是破。擦了「燙膚舒」後，比較不痛，據醫生說藥含有銀離子，可止
痛。

口乾，尤其是上顎，只能多喝水，滋潤一下。謝醫生說「液泌快」沒用。這個可
能是一輩子的功課。我目前先小口小口喝水，滋潤一下，沒事就「搭天橋」、
「扣齒」，用炁功的方法，看看有沒有助益。

後面就記錄放療這些天的心情和身體狀況。

* 日記錄

** 6/6 二 (1 天, 1 次) 59kg

第一次放療和化療。

12:00 才開始打化療，先打止吐針，然後打水 30 分鐘。最後才打化療藥：鉑、
5Fu。

護士說可能會有腸胃不適的狀況，不過，我感覺還好，沒有特別狀況。

放療，選擇的是螺旋刀，每星期定位一次，定位一次要八千台幣。躺在機台上，
戴上面罩，調整位置，進入機台，開始放療。感覺到放射器轉了 33 圈，大約六分
鐘結束，其實也沒有特别感覺。

** 6/7 三 (2 天, 2 次)

今天警衛說我的脖子有點黑，放療果然厲害，才照一次就可以發現變黑。

** 6/13 二 (8 天, 6 次) 58kg

口腔有點紅腫，覺得不大舒服，喉嚨裡一直覺得有一股濃痰，想吐也吐不出來。

謝醫生說要多吃多胺基酸，只有麸醯胺酸是不夠的。策略：多吃水果，百香果，奇異果，香吉士。

先前化療時，頭髮全掉光，現在頭髮細細毛毛地長出來，細細軟軟地很好摸。

** 6/14 三 (9 天, 7 次)

不吃西藥想吐，吃了藥一直打嗝。

** 6/17 六 (12 天, 9 次)

上顎和喉嚨開始覺得痛，口水很濃稠，一直覺得嘴巴裡鹹鹹的。後來發現，鹹鹹
的是口水，吃了「液泌快」才會分泌的口水味道。

** 6/20 二 (15 天, 11 次) 58kg

口水分泌比較差，有點口乾的感覺，買了條「白樂汀」保濕凝膠，用了後口腔比
較不痛了！這條「白樂汀」保濕凝膠到後來都還有用。

** 6/21 三 (16, 12)

狀況不錯口腔比較不痛。策略就是努力吃。努力吃水果，百香果香吉士檸檬汁。
脖子變硬了。

** 6/23 四 (18, 14)

去許中華醫生那拿了水包回來吃看看。口嘴巴裡一直有一股鹹鹹的味道，可能是
發炎，用必達定嗽口會痛。

** 6/27 二 (22) 59kg

- 白血球：4700
- 血小板：130K

舌頭表面也有點破，會痛。聽老婆建議，用椰子油漱口，效果不錯。

這幾天右邊鼻子開始流鼻血，徐醫生說正常，因為黏膜比較乾，所以會流鼻血，合理推論。

** 6/30～7/2

宜蘭步道之旅松羅步道，新寮瀑布，林美步道，美不勝收，重要的是都有體力走
完。

** 7/3 一 (28, 20)

左邊鼻子也流血了。吃百香果，酸啊，好痛。吃水果，第一次感到痛。

** 7/4 二 (29, 21) 58.5kg

- 白血球：9800
- 血小板：120K

上顎，喉嚨還是會痛，覺得鹹鹹的，是味覺改變。

晚上吃雞肉飯，高麗菜，筍絲，木瓜。很高興的是：味道都在，只是多了一點點
鹹味。

脖子開始覺得癢，不能抓，怕破了會感染。

** 7/5 三 (30, 22)

今天做斷層掃描，再一次確認腫瘤大小，下星期門診時再問醫生吧。

** 7/6 四 (31, 23)

早上起床後，喉嚨不痛，上顎也還好，椰子油可能有效。

中午吃餛飩麵。晚餐，炒飯，小雞腿一支，地瓜葉。食慾還不錯。

** 7/7 五 (32, 24)

昨天三餐飯後，均含著椰子油至少三十分鐘，今天的口腔狀況就很不錯，不痛，
連喉嚨也不痛。

** 7/8 六 (33)

早餐吃得真豐富，豬肉滿福堡一個，高鈣高纖奶。後來又去丹堤吃熏鷄薄餅，炒
蛋。奇怪的是食慾不錯，吃得也多，可是體重也不增加。

中午吃得也不錯，霸子牛排菲力牛排一份。

** 7/9 日 (34)

「白樂汀口腔凝膠」還是有用。昨天晚上覺得上顎很乾喉嚨也不舒服，想了想，
塗點百白樂汀可能有效，早上起來，上顎喉嚨都不大痛，但還是有點乾，狀况還
算良好。

** 7/10 一 (35, 25)

目前就只喉嚨和上顎痛，可以進食，没問題。花了一個小時走路回家，有點累，
休息了一小時。

** 7/11 二 (36,26) 57.5kg

WBC 10050 有點發炎。Platelet 125，正常，不再下降了。

起床後，喉嚨很痛，破得很嚴重，早餐吃得很慢，還是努力呑完十顆水餃，半顆
芭樂，一粒蛋，安素一瓶+麩醯胺酸，高鈣高纖奶，中藥+寬心飲二號。

徐醫生說喉嚨破，有白色念珠菌，要用漱口藥水，舌頭也破了，很痛。還好涼涼
的東西還是可以吃。

放療後約兩星期的時間會修復好，但是先決條件是營養要夠，還是要多吃麩醯胺
酸。

今天看斷層掃描的結果，和放療前的影像比對，鼻咽部的腫瘤消失得不明顯，頸
部的腫瘤倒是消到幾乎看不到，不過還是得看 MRI 結果比較準確。

MRI 要整個療程結束後一個月安排，所以還有時間爬山，練功，使用自然療法，
去治療腫瘤的部份。如果沒有消失，可能還得化療，真累。

** 7/12 三 (37, 27)

吃了白色念珠菌的藥，口腔的好像狀況好一點，没那麽痛了，中午可以吃甘泉魚麵。

** 7/13 四 (38, 28)

真奇怪，今天不知道為何特别累。

從亞東走回來的路上就覺得有點累了，回到家跟本没能做啥，直接躺在床上，到
12 點才起床。

中午吃皇家清燉牛肉麵，没吃完，留下一大碗。

下午繼續睡到四點。

晚上吃咖哩，感覺太辣了，吃得我滿頭汗。實際上是舌頭破了，才感到很辣、很痛。

** 7/14 五 (39, 29)

今天是用新的治療計畫，重新照影像定位，放射器轉了 24 圈，放射劑量應該比較
少吧？

脖子皮膚應該還是裂了，有點痛。

不知道為何，這兩天特别覺得累。

** 7/17 一 (42, 30)

今天照 24 圈。

星期五要再照影像，做縮小範圍治療計畫，預計做到星期六，共 2 次。所以總
共要做到 35 次。

明天要問如何得知這次治療成效，腫瘤是否消失？

後面重要的是，好何不復發，不擴散，不轉移。

** 7/18 二 (43, 31) 57.5kg

WBC 9000
白血球 12000

放療做到這星期六，共 35 次，最後 2 次也是縮小範圍。

8/25 排 MRI，8/29 看腫瘤消失狀況，主要是看淋巴節，用 MRI 會比正子攝影更精準。
如果要看全身或有無轉移，才用正子攝影。

化療結束，要吃半年 B 肝藥，免得會爆發，這是謝醫生說的。

徐醫生開的「燙膚舒」有效緩解頸部皮膚破裂的疼痛，比 NS-21 有效。因為，
NS-21 只是保濕，沒有治療功能，而且很貴，一支要台幣 1,200 元。

** 7/20 四 (45, 33)

「燙膚舒」有效，只是脖子還會變更黑。

再 2 次，全部放療療程結束。

** 7/21 五 (46, 34)

縮小範圍計畫，今天轉 24 圈。

做的時候不會有感覺，但今早起床感到喉嚨更痛，早餐有點吃不下，吃得很慢，不過還是得吃啊。

又瘦了一圈，只不過昨天中午沒吃而已。

** 7/22 六 (47, 35)

放療療程終於全部結束。

今天早上起床，口腔內好像比較不痛。

** 7/24 一 (49)

脖子上的破洞好似更大片，昨天夜裡還真的很痛，吃了瑪啡止痛也無效。

不知道為何舌面很痛？早上用椰子油漱口，希望有幫助。

** 7/25 二 (50) 55kg

體重掉得很快。

喉嚨很痛，吃不下固體的東西，只好喝安素。昨天喝了一天的安素，共 7 瓶，今天應該也只能喝安素吧。

徐醫生說，如果營養不夠，體重持續下降，修復能力會比較差，修復得較慢。如果只喝安素，要喝到 6 瓶。

** 7/27 四 (52)

沒想到這三天消耗安素的速度，飛快。

因為喉嚨和舌頭很痛，没辦法吃有一點硬度的食物，只得吃安素補充熱能。

早晚各一瓶倍力素或倍速，加上麩醯胺酸，其它時間共喝六瓶安素，再補以中華
愛玉、義美豆花。肚子是不大餓，可是到晚上還是脚軟。

脖子的傷，原本是 3 小片，現在都連在一起，成了一整大片。

** 7/28 五 (53)

繼續喝安素，早上多了一杯蔬果汁和鷄肉粥。

舌頭、喉嚨痛。

趁這機會順便斷食。

流鼻血的狀況已經改善很多，先前是一擤鼻涕就流出鮮血，現在已經不會流，即使有，也是一下下就乾，不會大量地流。血小板功能恢復，鼻腔內也没有太乾囉！

** 7/31 一 (56)

早上起床，覺得喉嚨不大痛，就是乾乾的讓上顎有點痛，可也不會很痛。重要的是，不再吐出血水，傷口應該好多了。

脖子的狀況也好很多，有一點流血，可是皮膚不會很紅，範圍也小了許多，好的狀況。

** 8/1 二 (57) 56kg

回診放射科，這兩天較好，頸部破皮範圍持續縮小中，現在要保持足夠營養，讓皮膚持續修復。

因為狀况狀好轉，止痛藥也少開了，直接約 8/E 再來看 MRI。

口乾和脖子硬是下一個課題。

未來還要追蹤胸部淋巴節有無擴散。

** 8/3 四 (59)

脖子的狀況也好很多了，受傷的範圍持續縮小。

今天試著吃一顆煎包，嗅覺還在，很香。嗯，舌頭很痛，沒味道。

** 8/7 一 (63)

舌頭的右側和喉嚨還是很痛。剛才發現，為何舌頭右側很痛？原來是接近舌根的地方，破了個約一公分的破洞，難怪會很痛。

目前就只有這樣不舒服的狀況。

** 8/8 二 (64) 56kg

舌頭破洞，很痛，謝醫生開了口內膏，看會不會比較快好。

口乾，尤其是上顎，只能多喝水，謝醫生說「液泌快」沒用。

9/5 早上照胸部 X 光，謝醫生判讀，再參看 MRI 結果，然後安排時間拆人工血管。

** 8/10 四 (66)

頸部皮膚的狀況算是好了，因為可以用水清洗，完全沒有痛的感覺。

** 8/14 (70)

早餐吃麵，肉包，高麗菜。吃什麼不重要，重要是舌頭有味道了，肉包的香，高麗菜的甜，而且舌頭也不大痛，哈哈。
不過，還是不能吃辣。中午吃豬脚飯，吃了口麻婆豆腐，痛啊！根本吃不下飯了。
晚上，吃得不錯。炒米粉，客家小炒，炒山蘇，不油不膩。

** 8/19 (74)

旅行結束，回到家了。
不得不說，最困擾的是右耳塞住了。
因為上山下山的，氣壓造成耳內壓力不平衡的感覺，一直沒辦法恢復正常，不舒服。
另外，舌頭痛的狀況尚未完全解除，碰到辣的食物，還是完全無法下嚥，很痛啊！但我可以確定的是，舌根的傷口已經好了很多，只剩小小的一個傷痕。

** 8/20 (75)

右耳還是塞住，聽不到。
舌面痛，舌根的破洞快好了。

** 8/25 (80) 57kg

右耳還是塞住。
舌根不痛。
舌面有點痛，不能吃辣。

還沒 6 點就起床了，沒辦法，頭好痛，起床吃了 2 顆止痛藥，沒比較好。後來進太空艙，也順便熱敷枕骨下緣，頭痛舒緩許多。但不知是止痛藥或是熱敷的效用，可確定的是肩頸很硬，該加强這個部位的拉筋。

早上去亞東做 MRI，大約 30 分鐘結束，8/29 回診看結果。即便沒有腫瘤也不代表痊瘉，癌瘤，真的很麻煩。

** 8/29 (84) 57kg

今天是看 MRI 結果。

鼻咽部平滑，腫瘤全消。

喉節附近還有一顆 1 公分大小的影像，可能是淋巴節腫瘤縮小後殘留，還要安排正子攝影，再追蹤。

其它部位均没有看到。

接下來要做正子攝影，看細胞活性，確認淋巴節那顆是否為腫瘤。

另外，要抽血追蹤是否有 EB 病毒，如果復發，EB 病毒指標會先升高。

耳朵塞住，是耳咽管腫，中耳狹窄積水，造成耳道內空氣壓力不平衡。鼻竇炎，鼻水多。這個算放療副作用，很可能會一直反復出現。

** 9/6  (92)

昨天，謝醫生說，還是要去看耳鼻喉科，看看耳朵塞住的狀況如何？不要掉以輕心。

今天，來到耳鼻喉科，張醫生說，做過放療，放射線照到鼻咽管會有這狀況。一般先吃藥，如果沒改善，可用耳膜穿刺，抽出中耳積水，如果還是不行，可以在耳膜裝中耳通氣管。唉！

順便可以看正子的結果：不大好。左、右鼻咽部和右頸第一區有亮亮，建議切片確認。

MD, 這次切片是左、右側的鼻咽部共抓了 5 塊肉，左三右二，痛死我了！

9／13 看切片結果。
9／19 還須回診徐醫生嗎？如果有回診謝醫生時再說吧。

中午吃大滷麵，加了點胡椒粉，有點辣辣，但已可以入口，舌頭不會受不了，意味著舌頭的傷，已經好得差不多了。
