#+BEGIN_COMMENT
.. title: 巴菲特和蒙格教你 投資的最高境界
.. date: 2017-08-07 12:00:00
.. updated:
.. comments: true
.. tags: Buffett, Munger
.. layout: post
.. category: investment
.. permalink:
.. options: toc:nil ^:{}
#+END_COMMENT


來源：[[https://www.stockfeel.com.tw/55090/][巴菲特和蒙格教你 投資的最高境界 – StockFeel 股感知識庫]]

股市的本質：股市本來就是以利潤為基礎，以本益比為基準的槓桿遊戲。

如果我們想把這個遊戲玩好。首先要明白遊戲的規則。根據公式：

#+BEGIN_EXAMPLE
股價=利潤(EPS) *本益比 (PE)
#+END_EXAMPLE

我們只要關注利潤和本益比這兩個變數就可以了。

這個遊戲玩的最好的是巴菲特 (Warren Buffett) ，它說遊戲很“簡單”，只要
學兩門課：
- 如何評估一家公司，也就是如何找到利潤成長的好公司 (跟利潤有關) 。
- 如何給企業估值，也就是買入的價格 (跟本益比有關) 。

* 第一門課：如何評估一家公司，也就是如何找到利潤成長的好公司。

如果是好公司，利潤會一直成長、成長、再成長，是沒有天花板的。

淨利潤成長來源無外乎 3 種情形：收入成長、毛利率提升、費用率降低。

- 營收持續成長，對應於提價、擴量
- 毛利率提升，意味著龍頭地位的鞏固，競爭力強；
- 費用率降低，表明公司管理的好。

這三項只要有一項能夠提升，就可能增加利潤。但最好是三項一起，才是穩定、
良性的增加公司利潤。比如如果營業收入不成長，只提高毛利跟控制成本，這樣
的利潤成長是有天花板的。

我們要找的就是那些營收連年成長，毛利率提升或穩定，能壓縮成本或穩定的公
司。

就算找到了還要考察下面一個重要的因素： *企業的護城河* 。

雖然公司利潤成長很快。但要看公司盈利能不能持續，是否容易受到攻擊。也就
是看企業的門檻夠不夠高。巴菲特最看重的就是企業的護城河，這是衡量一個公
司是好公司的重要因素。

這樣的例子太多，要求我們要找有門檻，有龐大護城河的企業。
遠離
- 無門檻
- 無特性
- 無品牌
- 無定價權
的企業。

科技行業有一個好處，如果你來處領先的地位，你的成長速度會非常快。科技公司的護城河就是創新，都是以創新進取獲得巨大的成長。

霍華德·馬克斯 (Howard Marks) 在《投資最重要的事 (The Most Important
Thing Illuminated) 》一書中提到：
#+BEGIN_QUOTE
買好的不如買得好 -- Howard Marks
#+END_QUOTE

* 第二門課：如何給企業估值，也就是買入的價格 (跟本益比有關)

本益比代表著一個公司的盈利能力收回成本需要的時間，說本益比不好理解，如
果用“槓桿”一詞來替代就很容易明白。簡單點說就是你想買這家公司，錢不夠
了，需要用多少倍槓桿來買。

成長股中，不同的公司，不同的階段，本益比也會有很大不同。比如現在人們買
銀行股只給 6 倍本益比、買家電股只給 15 倍本益比、買醫藥股給 40 倍本益
比、為什麼不同公司我們出的價錢不同，願意動用的槓桿也不同？這就跟我們的
預期、前景有關，跟利潤成長率也有很大關係。

#+BEGIN_EXAMPLE
股價＝利潤*本益比 (槓桿率)
#+END_EXAMPLE

股市最重要的道理：

#+BEGIN_QUOTE
第一、不要虧損。第二、不要忘了第一條。 -- 巴菲特
#+END_QUOTE

為了提醒我們這個道理，巴菲特老闆葛拉漢 (Benjamin Graham) 取了個名字叫
*“安全邊際”* ：

#+BEGIN_QUOTE
安全邊際總是取決於你付出的價格，它在某個時候價格會很大，其它一些時候價
格會很小，在價格更高時它便不復存在。 -- 葛拉漢
#+END_QUOTE

傳奇的基金經理彼得·林區 (Peter Lynch) 說“如果關於本益比你只記得一條，
那麼就是
#+BEGIN_QUOTE
永遠不買本益比過高的股票 -- Peter Lynch
#+END_QUOTE

看一下蒙格是怎麼做的。

#+BEGIN_QUOTE
有性格的人才能拿著現金坐在那裡什麼事也不做。我能有今天，靠的是不去追逐
平庸的機會。 -- 蒙格
#+END_QUOTE

我們的經驗往往驗證一個長久以來的觀念：只要做好準備，在人生中抓住幾個機
會。迅速地採取適當的行動，去做簡單而合乎邏輯的事情。這輩子的財富就會得
到極大的成長。

上面提到的這種機會很少，它們通常會落在不斷地尋找和等待，充滿求知慾望而
又熱衷於對各種不同的可能性作出分析的人頭上。這樣的機會來臨之後，如果獲
勝的機率極高，那麼動用過去的謹慎和耐心得來的資源，重重地壓下賭注就可以
了，賺大錢的秘訣並不在於頻繁的買進賣出，而在於耐心的等待。

關於耐心，巴菲特怎麼做的呢？巴菲特為了提醒自己耐心的重要性。在自己辦公
室放了一副泰德.威廉斯 (Theodore Williams) 擊球的圖片： *等待好球的出
現*

#+BEGIN_QUOTE
當機會來時，天上掉金子時要拿桶去接而不是湯勺 -- 巴菲特
#+END_QUOTE

而我們要做的就是既要買好的，又要買得好。也就是戴維斯“雙殺”。實際上就
是

- 葛拉漢的安全邊際理論
- 費雪 (Phil Fisher) 的成長股理論
- 蒙格的績優股理論

等三者的綜合，即等待“好的時機”以“好的價格”買入“好的股票”，實
現完美一擊，然後耐心持有，坐收上市公司和“市場先生”的雙重贈禮。
