#+BEGIN_COMMENT
.. title: 水果戰勝癌症
.. date: 2017-08-10 10:24:46
.. updated:
.. comments: true
.. layout: draft
.. tags: 癌, 食
.. category: health
.. permalink:
.. options: toc:nil ^:{}
#+END_COMMENT


[[http://health.businessweekly.com.tw/AArticleM.aspx?id=ARTL000093890][20 年戰勝 3 癌！醫師每天早上喝一杯「抗癌五彩蔬果汁」，常保體質弱鹼性]]

身為心臟內科醫師，從小又是運動健將的我，照理應當是身強體壯。從沒想過有一天自己會罹患癌症，而且還接連三種癌症！

從 32 歲那年開始，三種癌症陸續找上我─巨大細胞癌（骨癌）、腎臟癌與甲狀腺癌，抗癌期間長達十年，開刀無數次，忍受著一般人所
無法忍受的痛苦。但在經歷了這十年的痛苦經歷之後，我卻又奇蹟式的康復，而且身體狀況比罹患癌症之前更年輕、健康。

回首前塵，這一段抗癌歲月就好像是老天送給我的一樣禮物：讓我從煉獄般的痛苦裡重生，又毫髮無傷地還給我更健康的身心靈。抗癌
20 年間，為了活下去，窮盡各種抗癌方法，從正統的西醫治療，以至食物營養、天然植物複方、心靈療癒、氣功鍛鍊、藝術治療等，我
也有了抗癌心得，整合成一套癌症康復的方程式—CAM 整合療法。

CAM 整合療法讓我的身體得以通過三個癌症的歷練，獲得重生。這其中有許多不可思議的奇蹟。

色彩越多營養越高──多飲抗癌蔬果汁

每天在吃早餐前，我會先喝一杯蔬果汁來增加維他命 C、消化酵素，以及攝取植化素。從最新的營養學來看，五顏六色的蔬菜、水果
裡，具有被營養界熱烈推崇的「植化素」，可以消除人體的自由基，發揮抗氧化、增強免疫力、調節荷爾蒙的功能。每天只要能吃到五
顏六色的蔬菜、水果，就能攝取到充分且多元化的植化素，如胡蘿蔔素、茄紅素、兒茶素等。

植化素，就是植物所含的天然化學成分。它與維生素的特性不同，而且在蔬果的皮、根、莖、籽等部位含量最高。

每一種不同顏色的蔬果，都有獨特的植化素種類與功能，像是「花青素」和「阿 魏酸」含有抗老化的植化素；「檞皮素」含有高抗氧化
力的植化素，遠勝維生素 E、C；「楊梅素」則含有可以降血糖、趕走膽固醇的植化素；「綠原酸」含有可以幫人 體減重的植化素。

一般飲食療法所提倡的蔬果汁，都強調要使用無農藥的有機蔬果，以避免吃進農藥。但是有機蔬果價格昂貴，長期下來所費不貲。所以
我並未特別去買有機品，而是換個方式，設法將蔬菜、水果的殘留農藥去掉。

我特別喜歡在黃昏市場採買，而且一定挑當季盛產的蔬果，因為當季盛產的蔬果所含的營養成分最高，人體可以從中獲得最大好處，而
且價格上也比較經濟實惠。

我常喝的「抗癌五彩蔬果汁」，組合比例是 3 種蔬菜＋2 種水果，或是 3 種水果＋2 種蔬菜。蔬果種類主要有：花椰菜、高麗菜、蕃茄、蘋
果與鳳梨等。

切記， 花椰菜與高麗菜要連梗一起打汁。以花椰菜梗來說， 植化素高達 143 種，有類胡蘿蔔素、香豆素、生物類黃酮素、花青素等防癌
抗老元素，而且青花椰菜的功效比白花椰菜更好。

高麗菜有幫助傷口癒合的特性，我在癌症開刀後，就是因為常喝高麗菜汁，傷口復原的格外迅速。

*

photos 放大顯示

【材料配方範例】

● 蘋果 25 克（含有花青素、檞皮素、阿魏酸、綠原酸）
● 鳳梨 40 克（含有阿魏酸、綠原酸、鳳梨酵素）
● 番薯葉 40 克（含有楊梅素、檞皮素）
● 牛蒡 35 克（富含綠原酸）
● 加州黑棗梅 16 克（富含花青素、綠原酸）

【製作步驟】

STEP1. 在前一天晚上將要打汁的蔬菜、水果先做清洗。

STEP2. 清洗之後，加水浸泡在盆子裡，滴 1～2 滴天然配方的「環保蔬果清潔劑」浸泡一個晚上。

STEP3. 等第二天再洗一洗，就可以把大部份的農藥去掉，然後打成果菜汁飲用。

常保體質弱鹼性──吃出「3 鹼 1 酸」的飲食慣性

喝完抗癌五彩蔬果汁，接著我就會開始享用早餐，多半是三明治加牛奶，或是清粥小菜等簡單的食物，但是我一定遵守「3 鹼 1 酸」的原
則，也就是鹼性食物與酸性食物的比例為 3：1，這樣能夠使身體一直維持在弱鹼性的健康狀態。

以日常食材來說，鹼性食物多以青菜類為主；酸性食物是魚、肉、蛋和甜食等。如果經常吃太多酸性食物，身體也會慢慢變成酸性。酸
性體質是毒素的溫床，身體累積過多毒素，就會容易致癌。

如果完全不吃肉類，也容易造成蛋白質攝取不足的問題。因此，每餐維持 3 鹼 1 酸的飲食比例，最能讓身體活力充足，營養均衡，又「抗
癌五彩蔬果汁」配方與製作法能保持在良好的弱鹼性狀態。

另外，如果能以植物蛋白，如豆類、豆漿等素食來取代肉類，也有助於減低身體的毒素。這可依照個人的飲食習慣適度調整，以能夠期
適應和持之以恆為原則，不必太過勉強進行全素的飲食。

這篇[[la-empty-tummy][空腹吃水果勝癌症]]是從 line 直接轉出，來處不明，全文收錄於後。

* 附錄
** <<la-empty-tummy>>空腹吃水果勝癌症

台大郭銘雄(璁錡)醫師-生死的智慧，演講非常精采

*** ※空腹吃水果......(尤其是蘋果)
多虧了有關這個水果和果汁的電子郵件，它告訴了一個治癒癌症的戰略。我的成
功率為 80%。 癌症病人死不了了，不管你信還是不信，治療方法終於找到了。
對那些用常規療法治療癌症而死亡的患者，我深表遺憾。他們中沒幾個存活 5
年, 大多數用常規療法的人僅活兩三年而已。常規療法沒有任何作用，因為不用
常規療法治，病人也活兩三年。癌症病人一旦用了化療或放療，他們的細胞就中
毒了。就衰弱了。癌細胞就會因沒有強壯的抗體而得以迅速擴散。

*** ※常吃水果

一說到吃水果，我們就想到把水果 切成塊，大快朵頤。其實，沒那麼簡單。要
講究吃水果的方法和時間。什麼是正確方法呢？千萬別再飯後吃水果，一定要空
腹吃鮮果。這樣水果會起到身體殺毒作用，起到提供身體能量，消肥減瘦作用，
以及參與生化活動的作用。鮮果是重要食物。試想，你在吃兩片麵包後，又吃了
一片水果。本來水果是要透過胃壁進入腸子的，但被食物擋住了。與此同時，胃
發酵，變酸，水果一接觸到它們, 配著胃酸，整個食物就壞了。你會聽到有人抱
怨：我一吃西瓜就愛打嗝兒，我一吃榴槤就脹肚， 我一吃香蕉愛拉稀，等等。
那是因為水果與胃中腐敗的食物混合後產生的氣體造成的。但是你空腹吃水果，
就不會出像上述情況。白頭髮，禿頭謝頂，神經緊張，缺覺黑眼圈，在你空腹吃
鮮果以後，以上症狀一概消失。

郭銘雄(璁錡)博士研究：因所有的水果到了身體變成鹼性，所以像桔子、檸檬這
樣味道酸酸的水果，還是都屬於鹼性食物。只要正確掌握吃水果的時間，你就掌
握了問題的關鍵，讓水果助你美容，長壽，健康，富有活力，幸福和苗條。當你
想喝果汁，就喝鮮果汁，別喝罐裝果汁。也不要將水果或果汁加熱，否則除了味
道尚存，其他所有營養全部流失。 吃完整的水果比喝果汁好。如果非要喝果汁，
那就慢慢地一口一口地喝。讓果汁與唾液充分混合後再咽下。你還可以連續三天
只吃水果不吃它物，這樣你的身體得以清洗，容光煥發，眾人驚喜。

奇異果（獼猴桃）：小而精，富含鉀，鎂。維生素 E，和纖維質。維 C 含量是
桔子的兩倍。

一天一個蘋果，醫生找不到我。蘋果雖含維 C 低， 但它富含抗氧化劑並可提高
維 C 的活性，從而有利於降低結腸癌，心臟病和中風的發病率。

每日吃 2-4 個桔子：可抗感冒。降膽固醇，預防或化解腎結石，降低結腸癌風
險。

西瓜：含水 92%，是解渴最佳食品。所含大量的穀胱甘?能強化免疫系統。還含
有關鍵的番茄紅素，抗癌氧化劑，維 C， 以及鉀。

芭樂和木瓜是維 C 冠軍。芭樂還含有高纖維，能治便秘。木瓜富含糊蘿蔔素，
對眼睛有好處。

飯後喝涼水等於得癌症 。相信嗎？涼水能將剛吸收的油質立刻變成固態，從而
影響消化。固態油脂在酸的作用，變成小碎塊，比固體食物更易於被腸道吸收，
並附著在腸子的內壁。很快形成脂肪，導致癌的生成。所以餐後要喝熱飲。

如果將此文轉發 10 人，你至少救活一人的生命，甚至是你自己。

郭銘雄(璁錡)
